import { useState, useEffect } from "react";

const WIKI_ITEMS = {
  "Apples": "Apple", "Pears (European)": "Pear", "Pears (Asian)": "Asian_pear",
  "Peaches": "Peach", "Nectarines": "Nectarine", "Plums (European)": "Plum",
  "Cherries (Sour/Tart)": "Sour_cherry", "Cherries (Sweet)": "Cherry",
  "Quince": "Quince", "Mulberry": "Mulberry", "Pawpaw": "Asimina_triloba",
  "American Persimmon": "Persimmon", "Medlar": "Medlar", "Apricots": "Apricot",
  "Blueberries": "Blueberry", "Raspberries (Summer)": "Raspberry",
  "Raspberries (Fall-bearing)": "Raspberry", "Black Raspberries": "Black_raspberry",
  "Blackberries": "Blackberry", "Strawberries (June-bearing)": "Strawberry",
  "Strawberries (Day-neutral)": "Strawberry", "Grapes (Table)": "Grape",
  "Grapes (Wine)": "Grape", "Currants & Gooseberries": "Redcurrant",
  "Elderberry": "Sambucus_nigra", "Honeyberry / Haskap": "Lonicera_caerulea",
  "Hardy Kiwi": "Actinidia_arguta", "Serviceberry / Juneberry": "Amelanchier",
  "Figs (with protection)": "Common_fig", "Cornelian Cherry": "Cornus_mas",
  "Aronia / Chokeberry": "Aronia_melanocarpa", "Lingonberry": "Lingonberry",
  "Beach Plum": "Prunus_maritima", "Jostaberry": "Jostaberry",
  "Tomatoes": "Tomato", "Peppers (Sweet)": "Bell_pepper", "Peppers (Hot)": "Chili_pepper",
  "Zucchini / Summer Squash": "Zucchini", "Winter Squash": "Butternut_squash",
  "Pumpkins": "Pumpkin", "Cucumbers": "Cucumber", "Sweet Corn": "Sweet_corn",
  "Beans (Snap/Pole)": "Green_bean", "Beans (Lima/Edamame)": "Edamame",
  "Melons (Cantaloupe)": "Cantaloupe", "Watermelon": "Watermelon",
  "Eggplant": "Eggplant", "Sweet Potatoes": "Sweet_potato", "Potatoes": "Potato",
  "Okra": "Okra", "Ground Cherries": "Physalis_peruviana", "Tomatillos": "Tomatillo",
  "Lettuce": "Lettuce", "Spinach": "Spinach", "Kale": "Kale",
  "Swiss Chard": "Chard", "Broccoli": "Broccoli", "Cauliflower": "Cauliflower",
  "Cabbage": "Cabbage", "Brussels Sprouts": "Brussels_sprout", "Peas": "Pea",
  "Carrots": "Carrot", "Beets": "Beetroot", "Radishes": "Radish", "Turnips": "Turnip",
  "Parsnips": "Parsnip", "Onions": "Onion", "Garlic": "Garlic", "Leeks": "Leek",
  "Kohlrabi": "Kohlrabi", "Asian Greens": "Bok_choy",
  "Radicchio / Endive": "Radicchio", "Napa Cabbage": "Napa_cabbage",
  "Asparagus": "Asparagus", "Rhubarb": "Rhubarb", "Sunchokes": "Jerusalem_artichoke",
  "Horseradish": "Horseradish", "Fiddlehead Ferns": "Fiddlehead_fern",
  "Sorrel": "Sorrel", "Groundnuts": "Apios_americana",
  "Artichokes (annual)": "Globe_artichoke", "Celeriac": "Celeriac",
  "Florence Fennel": "Fennel", "Thyme": "Thyme", "Oregano": "Oregano",
  "Sage": "Salvia_officinalis", "Chives": "Chives", "Mint": "Mentha",
  "French Tarragon": "Tarragon", "Lovage": "Lovage", "Basil": "Basil",
  "Cilantro": "Coriander", "Dill": "Dill", "Parsley": "Parsley", "Rosemary": "Rosemary",
  "Jujube": "Jujube", "Che Fruit": "Maclura_tricuspidata",
  "Chestnuts": "Chestnut", "Hazelnuts": "Hazelnut", "Black Walnuts": "Juglans_nigra",
  "Butternuts": "Juglans_cinerea", "Hickory": "Carya_ovata", "Heartnuts": "Juglans_ailantifolia",
  "Goji Berry": "Goji_berry", "Goumi": "Elaeagnus_multiflora", "Wineberry": "Rubus_phoenicolasius",
  "Rutabaga": "Rutabaga", "Mache / Corn Salad": "Valerianella_locusta",
  "Claytonia": "Claytonia_perfoliata", "Hops": "Humulus_lupulus",
};

// Static fallback images for items where Wikipedia API fails or returns no/wrong thumbnail
// Also used to ensure duplicate wiki keys get unique images
const FALLBACK_IMAGES = {
  // Override botanical illustrations with real photos
  "Garlic": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/GarlicBasket.jpg/200px-GarlicBasket.jpg",
  "Peach": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Autumn_Red_peaches.jpg/200px-Autumn_Red_peaches.jpg",
  "Sour_cherry": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Sauerkirschen.jpg/200px-Sauerkirschen.jpg",
  // Wikipedia API returns no thumbnail for these
  "Black_raspberry": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Rubus_occidentalis_2008_07_06.JPG/200px-Rubus_occidentalis_2008_07_06.JPG",
  "Napa_cabbage": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Napa_cabbages.png/200px-Napa_cabbages.png",
  "Jostaberry": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Ribes_nidigrolaria.jpg/200px-Ribes_nidigrolaria.jpg",
  "Asparagus": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Asparagus.jpg/200px-Asparagus.jpg",
  // Unique images for items sharing the same wiki key
  "Nectarine": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Nectarine.jpg/200px-Nectarine.jpg",
  "Raspberry_fall": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Red_Raspberry_%28Rubus_idaeus%29_-_Thunder_Bay%2C_Ontario.jpg/200px-Red_Raspberry_%28Rubus_idaeus%29_-_Thunder_Bay%2C_Ontario.jpg",
  "Strawberry_dayneutral": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/PerfectStrawberry.jpg/200px-PerfectStrawberry.jpg",
  "Grape_wine": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Kyoho-grape.jpg/200px-Kyoho-grape.jpg",
};

const DATA = [
  { category: "Tree Fruits", icon: "🍎", color: "#C0392B", bg: "#FDEDEC", items: [
    { name: "Apples", diff: 1, desc: "Best overall fruit tree for CT. Disease-resistant cultivars reduce spray needs dramatically. 280+ CT farms grow them commercially.", varieties: "Liberty, Enterprise, Freedom, GoldRush, Pristine, CrimsonCrisp, Honeycrisp, Macoun, McIntosh, Cortland, Empire, Northern Spy, Golden Russet", notes: "Need 2+ varieties for pollination. Semi-dwarf rootstock (M.26, G.935) recommended. Crabapples serve as universal pollinators.", urdu: { name: "سیب", desc: "کنیکٹیکٹ کے لیے بہترین پھل دار درخت۔ بیماری مزاحم اقسام سپرے کی ضرورت بہت کم کر دیتی ہیں۔ 280 سے زیادہ فارم تجارتی طور پر اُگاتے ہیں۔", varieties: "لبرٹی، انٹرپرائز، فریڈم، گولڈ رش، پرسٹین، کرمسن کرسپ، ہنی کرسپ، مکاؤن، مکنٹوش، کورٹلینڈ، ایمپائر، ناردرن سپائی، گولڈن رسٹ", notes: "جرگ کے لیے 2 یا زیادہ اقسام ضروری ہیں۔ نیم بونے جڑ کی سفارش۔ جنگلی سیب عالمگیر جرگ کنندہ ہیں۔" } },
    { name: "Pears (European)", diff: 2, desc: "Reliable with fire blight–resistant selections. Ripen off the tree for best texture.", varieties: "Harrow Sweet, Harrow Delight, Moonglow, Blake's Pride, Potomac, Seckel", notes: "Need 2 varieties. Bartlett and Seckel won't cross-pollinate each other.", urdu: { name: "ناشپاتی (یورپی)", desc: "فائر بلائٹ مزاحم اقسام کے ساتھ قابل اعتماد۔ بہترین ذائقے کے لیے درخت سے اتارنے کے بعد پکائیں۔", varieties: "ہیرو سویٹ، ہیرو ڈیلائٹ، مون گلو، بلیکس پرائیڈ، پوٹومیک، سیکل", notes: "2 اقسام ضروری ہیں۔ بارٹلیٹ اور سیکل ایک دوسرے کی جرگ نہیں کر سکتے۔" } },
    { name: "Pears (Asian)", diff: 2, desc: "Perform exceptionally well in CT. Crisp texture, eaten fresh. A Warren, CT grower maintains 11 trees successfully.", varieties: "Shinseiki, Hosui, Chojuro, 20th Century, Shinko, Shin Li", notes: "Need 2 varieties. More disease-resistant than European pears.", urdu: { name: "ناشپاتی (ایشیائی)", desc: "کنیکٹیکٹ میں بہترین کارکردگی۔ کرکرا ذائقہ، تازہ کھایا جاتا ہے۔", varieties: "شنسیکی، ہوسوئی، چوجورو، 20ویں صدی، شنکو، شن لی", notes: "2 اقسام ضروری ہیں۔ یورپی ناشپاتیوں سے زیادہ بیماری مزاحم۔" } },
    { name: "Peaches", diff: 3, desc: "Adapted to Zone 6 but late spring frost kills blossoms many years. Site selection critical.", varieties: "Reliance (hardiest, to -25°F), Contender (late-bloom), Red Haven, Madison, Harrow Beauty, Curlfree (leaf curl resistant)", notes: "Self-fertile. Plant on NORTH slope to delay bloom — UConn recommendation.", urdu: { name: "آڑو", desc: "زون 6 کے لیے موزوں لیکن دیر بہار کے پالے سے پھول اکثر سالوں میں مر جاتے ہیں۔ جگہ کا انتخاب اہم ہے۔", varieties: "ریلائنس (سب سے سخت جان)، کنٹینڈر (دیر سے کھلنے والا)، ریڈ ہیون، میڈیسن، ہیرو بیوٹی، کرل فری", notes: "خود بارور۔ پھول دیر سے کھلنے کے لیے شمالی ڈھلوان پر لگائیں۔" } },
    { name: "Nectarines", diff: 3, desc: "Same care as peaches. Fuzzless skin bruises easier but worth trying alongside peaches.", varieties: "Mericrest (bred at UNH for New England), Hardired", notes: "Self-fertile. Same frost-avoidance strategy as peaches.", urdu: { name: "شفتالو", desc: "آڑو جیسی دیکھ بھال۔ بغیر رُوئیں کی جلد جلدی زخمی ہوتی ہے لیکن آڑو کے ساتھ اُگانے کے قابل ہے۔", varieties: "میری کریسٹ (نیو انگلینڈ کے لیے تیار)، ہارڈ ریڈ", notes: "خود بارور۔ آڑو جیسی پالے سے بچاؤ کی حکمت عملی۔" } },
    { name: "Plums (European)", diff: 2, desc: "Far more reliable than Japanese types. Bloom later, many self-fertile, tolerate humidity.", varieties: "Stanley (classic prune plum), Italian/Fellenberg, Green Gage (superb flavor), Blue Damson, Mount Royal", notes: "Most are self-fertile. Watch for black knot disease. Japanese-American hybrids (Superior, Toka) offer a compromise.", urdu: { name: "آلو بخارا (یورپی)", desc: "جاپانی اقسام سے کہیں زیادہ قابل اعتماد۔ دیر سے کھلتے ہیں، اکثر خود بارور، نمی برداشت کرتے ہیں۔", varieties: "اسٹینلی (کلاسک)، اٹالین/فیلنبرگ، گرین گیج (لاجواب ذائقہ)، بلیو ڈیمسن، ماؤنٹ رائل", notes: "اکثر خود بارور ہیں۔ بلیک ناٹ بیماری کا خیال رکھیں۔" } },
    { name: "Cherries (Sour/Tart)", diff: 2, desc: "Significantly more reliable than sweet cherries in CT humidity. Self-fertile, very hardy.", varieties: "Montmorency (classic pie cherry), North Star (dwarf 8–10 ft), Balaton (sweeter Hungarian type)", notes: "Self-fertile — one tree sufficient. Excellent for pies and preserves.", urdu: { name: "کھٹی چیری", desc: "کنیکٹیکٹ کی نمی میں میٹھی چیریوں سے کہیں زیادہ قابل اعتماد۔ خود بارور، بہت سخت جان۔", varieties: "مونٹمورینسی (کلاسک پائی چیری)، نارتھ اسٹار (بونا)، بالاٹون (میٹھی ہنگیرین قسم)", notes: "خود بارور — ایک درخت کافی ہے۔ پائیز اور مربے کے لیے بہترین۔" } },
    { name: "Cherries (Sweet)", diff: 3, desc: "Possible with self-fertile varieties. Brown rot is the main challenge in humid summers.", varieties: "BlackGold, WhiteGold (both Cornell releases for NE), Stella, Lapins (crack-resistant)", notes: "Choose self-fertile varieties. Good air circulation essential.", urdu: { name: "میٹھی چیری", desc: "خود بارور اقسام کے ساتھ ممکن۔ نمی والی گرمیوں میں بھوری سڑاند اصل چیلنج ہے۔", varieties: "بلیک گولڈ، وائٹ گولڈ (دونوں کارنیل ریلیز)، سٹیلا، لیپنز", notes: "خود بارور اقسام چنیں۔ اچھی ہوا کی گردش ضروری ہے۔" } },
    { name: "Quince", diff: 1, desc: "Low-maintenance, self-fertile, few pest problems. Fragrant fruit for preserves.", varieties: "Champion, Pineapple, Orange, Aromatnaya (Russian)", notes: "Self-fertile. Susceptible to fire blight and cedar-quince rust.", urdu: { name: "بہی", desc: "کم دیکھ بھال، خود بارور، کم کیڑوں کے مسائل۔ خوشبودار پھل مربے کے لیے۔", varieties: "چیمپئن، پائن ایپل، اورنج، اروماٹنایا (روسی)", notes: "خود بارور۔ فائر بلائٹ اور سیڈر-بہی زنگ کا خطرہ۔" } },
    { name: "Mulberry", diff: 1, desc: "Essentially carefree. Long harvest June–Aug. Stains everything; attracts birds.", varieties: "Illinois Everbearing (standard), Gerardi Dwarf (6–8 ft for small spaces)", notes: "Self-fertile. Plant away from walkways (staining).", urdu: { name: "شہتوت", desc: "بالکل آسان۔ جون سے اگست تک لمبی فصل۔ سب کچھ داغدار کر دیتا ہے؛ پرندوں کو کھینچتا ہے۔", varieties: "الینوائے ایور بیئرنگ (معیاری)، جرارڈی بونا (چھوٹی جگہوں کے لیے)", notes: "خود بارور۔ راستوں سے دور لگائیں (داغ لگنے کی وجہ سے)۔" } },
    { name: "Pawpaw", diff: 2, desc: "Native tree with tropical-flavored fruit (custard/mango/banana). Shade young trees first 2 summers.", varieties: "Shenandoah, Susquehanna, Potomac (all Peterson selections), Sunflower", notes: "Need 2 genetically different trees (self-incompatible). Pollinated by flies — hand pollination helps.", urdu: { name: "پاپا", desc: "مقامی درخت جس کا پھل اشنکٹبندیی ذائقے والا ہے (کسٹرڈ/آم/کیلا)۔ پہلی 2 گرمیوں میں سایہ دیں۔", varieties: "شنینڈوا، سسکوہینا، پوٹومیک (تمام پیٹرسن سلیکشنز)، سن فلاور", notes: "2 جینیاتی طور پر مختلف درخت ضروری ہیں۔ مکھیوں سے جرگ ہوتی ہے — ہاتھ سے جرگ مددگار ہے۔" } },
    { name: "American Persimmon", diff: 1, desc: "Native, virtually zero maintenance, hardy to Zone 4. Do NOT plant Japanese types here.", varieties: "Prok, Meader (rare self-fertile variety), Yates, Early Golden", notes: "Most are dioecious — plant several, or choose Meader. Astringent until fully ripe.", urdu: { name: "جاپانی پھل (امریکی)", desc: "مقامی، تقریباً صفر دیکھ بھال، زون 4 تک سخت جان۔ یہاں جاپانی اقسام نہ لگائیں۔", varieties: "پروک، میڈر (نایاب خود بارور قسم)، ییٹس، ارلی گولڈن", notes: "اکثر دو جنسی ہیں — کئی لگائیں، یا میڈر چنیں۔ مکمل پکنے تک کسیلا ہوتا ہے۔" } },
    { name: "Medlar", diff: 1, desc: "Hardy, self-fertile, pest-free. Available from Cricket Hill Garden (Thomaston, CT nursery).", varieties: "Nottingham (best flavor), Breda Giant, Royal", notes: "Fruit must 'blet' (soften after picking) before eating.", urdu: { name: "مسپولا", desc: "سخت جان، خود بارور، کیڑوں سے پاک۔ کرکٹ ہل گارڈن (تھامسٹن، CT) سے دستیاب۔", varieties: "ناٹنگھم (بہترین ذائقہ)، بریڈا جائنٹ، رائل", notes: "پھل کھانے سے پہلے 'بلیٹ' (توڑنے کے بعد نرم) ہونا ضروری ہے۔" } },
    { name: "Apricots", diff: 4, desc: "THE gamble. Blooms 2–3 wks before peaches — frost kills crop most years. One western CT grower: 1 fruit in 20 years.", varieties: "Goldcot (bred at MSU, latest bloom), Harglow (Canadian, late bloom)", notes: "Plant on north slope. Expect crop failures most years.", urdu: { name: "خوبانی", desc: "سب سے بڑا جوا۔ آڑو سے 2-3 ہفتے پہلے کھلتی ہے — زیادہ تر سالوں میں پالا فصل تباہ کر دیتا ہے۔", varieties: "گولڈ کاٹ (سب سے دیر سے کھلنے والا)، ہارگلو (کینیڈین، دیر سے کھلنے والا)", notes: "شمالی ڈھلوان پر لگائیں۔ زیادہ تر سالوں میں فصل کی ناکامی کی توقع رکھیں۔" } },
    { name: "Jujube", diff: 4, desc: "Marginal — trees survive Zone 6b but short, cool summers often prevent optimal fruit ripening.", varieties: "Li (largest fruit), Lang, Sugar Cane (sweetest)", notes: "Worth experimenting against south-facing wall with reflected heat. Self-fertile.", urdu: { name: "بیر", desc: "کم عملی — درخت زون 6b میں زندہ رہتے ہیں لیکن مختصر ٹھنڈی گرمیاں اکثر پھل پکنے سے روکتی ہیں۔", varieties: "لی (سب سے بڑا پھل)، لینگ، شوگر کین (سب سے میٹھا)", notes: "جنوبی دیوار کے سامنے منعکس گرمی کے ساتھ تجربہ کرنے کے قابل۔ خود بارور۔" } },
    { name: "Che Fruit", diff: 3, desc: "Maclura tricuspidata. Trees cold-hardy to -20F but fruit ripening unreliable in Zone 6.", varieties: "Norris (available from Cricket Hill Garden, Thomaston CT)", notes: "Related to Osage orange. Sweet, mulberry-like fruit when fully ripe. Dioecious.", urdu: { name: "چی فروٹ", desc: "درخت سردی میں -20°F تک برداشت کرتے ہیں لیکن زون 6 میں پھل پکنا غیر یقینی ہے۔", varieties: "نورس (کرکٹ ہل گارڈن، تھامسٹن CT سے دستیاب)", notes: "اوسیج اورنج کا رشتہ دار۔ مکمل پکنے پر میٹھا، شہتوت جیسا پھل۔ دو جنسی۔" } },
  ]},
  { category: "Nut Trees", icon: "🌰", color: "#795548", bg: "#EFEBE9", items: [
    { name: "Chestnuts", diff: 2, desc: "Chinese and hybrid chestnuts are blight-resistant and thrive in NE acidic soils. Bear in 3-5 years from grafted stock.", varieties: "Colossal (large nut), Dunstan hybrids (blight-resistant), Qing (Chinese, sweet)", notes: "Need 2 varieties for cross-pollination. American chestnut restoration hybrids also available.", urdu: { name: "شاہ بلوط", desc: "چینی اور ہائبرڈ شاہ بلوط بلائٹ مزاحم ہیں اور شمال مشرقی تیزابی مٹی میں پھلتے پھولتے ہیں۔ پیوند شدہ پودوں سے 3-5 سال میں پھل دیتے ہیں۔", varieties: "کولوسل (بڑا گری دار)، ڈنسٹن ہائبرڈز (بلائٹ مزاحم)، چنگ (چینی، میٹھا)", notes: "جرگ کے لیے 2 اقسام ضروری ہیں۔ امریکی شاہ بلوط بحالی کے ہائبرڈز بھی دستیاب ہیں۔" } },
    { name: "Hazelnuts", diff: 2, desc: "American-European hybrids combine native disease resistance with larger European nut size. Produce in 3-4 years.", varieties: "Yamhill, Jefferson, Theta (all OSU releases, Eastern Filbert Blight resistant)", notes: "Plant in groups for wind pollination. Arbor Day Foundation and Badgersett offer NE-adapted selections.", urdu: { name: "فندق", desc: "امریکی-یورپی ہائبرڈز مقامی بیماری مزاحمت کو بڑے یورپی گری کے سائز کے ساتھ ملاتے ہیں۔ 3-4 سال میں پیداوار۔", varieties: "یامہل، جیفرسن، تھیٹا (تمام OSU ریلیز، فلبرٹ بلائٹ مزاحم)", notes: "ہوا سے جرگ کے لیے گروپوں میں لگائیں۔" } },
    { name: "Black Walnuts", diff: 2, desc: "Native, extremely hardy (Zone 4). Richly flavored nuts prized for baking. Very long-lived trees.", varieties: "Thomas (thin-shelled), Sparrow (thin-shelled, easier cracking)", notes: "CAUTION: Roots produce juglone, toxic to tomatoes, peppers, blueberries. Keep 50-80 ft from veggie gardens.", urdu: { name: "کالا اخروٹ", desc: "مقامی، انتہائی سخت جان (زون 4)۔ بھرپور ذائقے والے گری دار میوے بیکنگ کے لیے قیمتی۔ بہت لمبی عمر کے درخت۔", varieties: "تھامس (پتلے خول والا)، سپیرو (پتلے خول والا، آسان توڑنے والا)", notes: "احتیاط: جڑیں جگلون پیدا کرتی ہیں جو ٹماٹر، مرچ، بلیو بیری کے لیے زہریلا ہے۔ سبزیوں کے باغ سے 50-80 فٹ دور رکھیں۔" } },
    { name: "Butternuts", diff: 3, desc: "Native white walnut, hardy to Zone 3. Milder flavor than black walnut. Endangered by butternut canker.", varieties: "Seek canker-resistant selections from specialty nurseries", notes: "Threatened species — growing them supports conservation. Less juglone than black walnut.", urdu: { name: "سفید اخروٹ", desc: "مقامی سفید اخروٹ، زون 3 تک سخت جان۔ کالے اخروٹ سے ہلکا ذائقہ۔ کینکر کی وجہ سے خطرے میں۔", varieties: "خصوصی نرسریوں سے کینکر مزاحم اقسام تلاش کریں", notes: "خطرے سے دوچار نوع — انہیں اُگانا تحفظ کی حمایت کرتا ہے۔ کالے اخروٹ سے کم جگلون۔" } },
    { name: "Hickory", diff: 3, desc: "Shagbark hickory is native, produces sweet nuts similar to pecans. Slow to bear (8-10 yrs) but extremely long-lived.", varieties: "Weschcke, Yoder #1, Grainger. Hicans (hickory-pecan hybrids): Burton", notes: "Hicans offer larger nuts with easier cracking. Northern pecans (Kanza, Pawnee) marginal in Zone 6b.", urdu: { name: "ہکوری", desc: "شیگ بارک ہکوری مقامی ہے، پیکان جیسے میٹھے گری دار میوے پیدا کرتی ہے۔ دیر سے پھل دیتی ہے (8-10 سال) لیکن انتہائی لمبی عمر۔", varieties: "ویشکی، یوڈر #1، گرینجر۔ ہائیکنز (ہکوری-پیکان ہائبرڈ): برٹن", notes: "ہائیکنز بڑے گری دار میوے آسان توڑنے کے ساتھ فراہم کرتے ہیں۔" } },
    { name: "Heartnuts", diff: 2, desc: "Japanese walnut (Juglans ailantifolia var. cordiformis). Heart-shaped nuts crack out in whole halves. Hardy to Zone 5.", varieties: "Campbell CW3, Imshu", notes: "Less juglone concern than black walnut. Attractive ornamental tree. Self-fertile but better with cross-pollination.", urdu: { name: "دل اخروٹ", desc: "جاپانی اخروٹ۔ دل کی شکل کے گری دار میوے پوری آدھی شکل میں ٹوٹتے ہیں۔ زون 5 تک سخت جان۔", varieties: "کیمبل CW3، امشو", notes: "کالے اخروٹ سے کم جگلون کا خدشہ۔ خوبصورت سجاوٹی درخت۔ خود بارور لیکن جرگ سے بہتر۔" } },
  ]},
  { category: "Berries & Small Fruits", icon: "🫐", color: "#6C3483", bg: "#F4ECF7", items: [
    { name: "Blueberries", diff: 1, desc: "CT's acidic soil (pH 4.8–5.5) is PERFECT — no amendment needed. Bird netting essential.", varieties: "Duke (early, late-blooming avoids frost), Patriot (heavy soil OK), Bluecrop (mid, industry standard), Blueray, Jersey (late, long-lived), Elliott (latest), Chandler (huge berries)", notes: "Plant 2–3 varieties for cross-pollination + extended harvest. Mulch 4\" woodchips.", urdu: { name: "بلیو بیری", desc: "کنیکٹیکٹ کی تیزابی مٹی (pH 4.8–5.5) بالکل مثالی ہے — کسی ترمیم کی ضرورت نہیں۔ پرندوں کا جال ضروری۔", varieties: "ڈیوک (ابتدائی)، پیٹریاٹ (بھاری مٹی ٹھیک)، بلیو کراپ (درمیانی، صنعتی معیار)، جرسی (دیر، لمبی عمر)، چاندلر (بڑی بیریاں)", notes: "جرگ اور طویل فصل کے لیے 2-3 اقسام لگائیں۔ 4 انچ لکڑی کے چپس سے ملچ کریں۔" } },
    { name: "Raspberries (Summer)", diff: 1, desc: "CT climate excels for raspberries. One large crop in July.", varieties: "Latham (extremely hardy), Killarney, Nova (thornless, disease-resistant), Canby (nearly thornless). Purple: Royalty (large, very sweet)", notes: "Prune out fruited canes after harvest. Trellis recommended. Royalty purple raspberry is exceptionally productive.", urdu: { name: "رس بھری (گرمائی)", desc: "کنیکٹیکٹ کی آب و ہوا رس بھری کے لیے بہترین ہے۔ جولائی میں ایک بڑی فصل۔", varieties: "لاتھم (انتہائی سخت جان)، کلارنی، نووا (بے کانٹا، بیماری مزاحم)، کینبی۔ جامنی: رائلٹی (بڑی، بہت میٹھی)", notes: "فصل کے بعد پھل دینے والی شاخیں کاٹ دیں۔ ٹریلس کی سفارش۔" } },
    { name: "Raspberries (Fall-bearing)", diff: 1, desc: "Fruit on new wood Aug–frost. Simpler pruning (mow all canes in spring). May dodge SWD pressure.", varieties: "Heritage (most planted, reliable), Caroline (larger berries, excellent flavor), Joan J (thornless)", notes: "Can mow entire patch to ground each spring. Very easy management.", urdu: { name: "رس بھری (خزاں والی)", desc: "نئی لکڑی پر اگست سے پالے تک پھل۔ آسان کٹائی (بہار میں تمام شاخیں کاٹ دیں)۔", varieties: "ہیریٹیج (سب سے زیادہ لگائی جانے والی)، کیرولین (بڑی بیریاں)، جون جے (بے کانٹا)", notes: "ہر بہار میں پورا حصہ زمین تک کاٹ سکتے ہیں۔ بہت آسان انتظام۔" } },
    { name: "Black Raspberries", diff: 2, desc: "Unique rich flavor. More disease-prone than red types but worth growing.", varieties: "Jewel (most widely planted, disease-tolerant), Bristol", notes: "Tip-layer to propagate. Keep away from wild brambles (disease vector).", urdu: { name: "کالی رس بھری", desc: "منفرد بھرپور ذائقہ۔ سرخ اقسام سے زیادہ بیماری کا شکار لیکن اُگانے کے قابل۔", varieties: "جیول (سب سے زیادہ لگائی جانے والی، بیماری برداشت)، برسٹل", notes: "نوک تہہ بندی سے افزائش کریں۔ جنگلی جھاڑیوں سے دور رکھیں (بیماری کا ذریعہ)۔" } },
    { name: "Blackberries", diff: 2, desc: "Modern thornless varieties transformed northern blackberry growing.", varieties: "Triple Crown (thornless, excellent), Chester (very hardy, late), Ouachita (erect, disease-resistant), Illini Hardy (thorned, most cold-tolerant), Prime-Ark Freedom (primocane, thornless)", notes: "Prime-Ark Freedom fruits on new wood — confirmed successful Zone 6b.", urdu: { name: "بلیک بیری", desc: "جدید بے کانٹا اقسام نے شمالی بلیک بیری کاشت کو بدل دیا۔", varieties: "ٹرپل کراؤن (بے کانٹا، عمدہ)، چیسٹر (بہت سخت جان)، اواچیتا (بیماری مزاحم)، الینی ہارڈی (سب سے سردی برداشت)، پرائم آرک فریڈم (بے کانٹا)", notes: "پرائم آرک فریڈم نئی لکڑی پر پھل دیتا ہے — زون 6b میں کامیاب ثابت۔" } },
    { name: "Strawberries (June-bearing)", diff: 1, desc: "One large crop in June. Renovate beds after harvest for multi-year production.", varieties: "Earliglow (#1 NE pick, exceptional flavor), Honeoye (early, very productive), Jewel, Allstar (disease-resistant, beginner-friendly), Cabot (very large), Malwina (latest, highest sugar)", notes: "Remove first-year flowers for stronger plants. Mulch with straw.", urdu: { name: "سٹرابیری (جون والی)", desc: "جون میں ایک بڑی فصل۔ کئی سالوں کی پیداوار کے لیے فصل کے بعد بستر کی تجدید کریں۔", varieties: "ارلی گلو (بہترین ذائقہ)، ہنیائے (ابتدائی، بہت پیداواری)، جیول، آل سٹار (بیماری مزاحم، شروع کرنے والوں کے لیے)، میلوینا (سب سے زیادہ شکر)", notes: "مضبوط پودوں کے لیے پہلے سال کے پھول ہٹا دیں۔ بھوسے سے ملچ کریں۔" } },
    { name: "Strawberries (Day-neutral)", diff: 1, desc: "Continuous production June through frost. Hedges against late frost destroying crop.", varieties: "Seascape (heavy producer), Albion (firm, sweet), Tristar", notes: "Treat as annuals or short-lived perennials. Remove runners for best yields.", urdu: { name: "سٹرابیری (مسلسل پھلنے والی)", desc: "جون سے پالے تک مسلسل پیداوار۔ دیر کے پالے سے فصل تباہ ہونے کے خلاف تحفظ۔", varieties: "سی سکیپ (بھاری پیداوار)، البیون (سخت، میٹھا)، ٹرائی سٹار", notes: "سالانہ یا مختصر عمر کے بارہماسی کے طور پر رکھیں۔ بہترین پیداوار کے لیے رنرز ہٹائیں۔" } },
    { name: "Grapes (Table)", diff: 2, desc: "CT has 40+ wineries — this climate works. Table grapes for fresh eating and juice.", varieties: "Concord (bulletproof, the classic), Niagara (white/green), Reliance (red seedless, very hardy), Canadice (red seedless), Mars, Jupiter (blue seedless)", notes: "Need sturdy trellis. Prune hard late winter. Spotted lanternfly threat now in Litchfield County.", urdu: { name: "انگور (کھانے کے)", desc: "کنیکٹیکٹ میں 40 سے زیادہ وائنریز ہیں — یہ آب و ہوا کام کرتی ہے۔ تازہ کھانے اور جوس کے لیے۔", varieties: "کونکورڈ (کلاسک)، نیاگرا (سفید/سبز)، ریلائنس (سرخ بیج کے بغیر، بہت سخت جان)، کینیڈائس، مارس، جوپیٹر", notes: "مضبوط ٹریلس ضروری۔ دیر سردیوں میں سخت کٹائی۔ لچفیلڈ کاؤنٹی میں لالٹین مکھی کا خطرہ۔" } },
    { name: "Grapes (Wine)", diff: 3, desc: "Cold-hardy hybrids from U of MN revolutionized northern winemaking.", varieties: "Marquette (to -30°F, premier cold-climate red), Frontenac, Frontenac Gris, La Crescent (aromatic white), Cayuga White, Seyval Blanc, Chambourcin", notes: "Disease management program essential in CT humidity.", urdu: { name: "انگور (شراب)", desc: "مینیسوٹا یونیورسٹی کی سردی برداشت ہائبرڈز نے شمالی شراب سازی میں انقلاب برپا کیا۔", varieties: "مارکیٹ (سردی میں بہترین سرخ)، فرانٹیناک، لا کریسنٹ (خوشبودار سفید)، کایوگا وائٹ، سیوال بلانک، شیمبرسن", notes: "کنیکٹیکٹ کی نمی میں بیماری کے انتظام کا پروگرام ضروری۔" } },
    { name: "Currants & Gooseberries", diff: 1, desc: "Thrive in CT's cool, humid climate. Partial shade OK. Few pest problems.", varieties: "Red Lake, Rovada (excellent fresh), Jonkheer Van Tets, Titania (black, rust-resistant), Pink Champagne, White Imperial, Invicta (gooseberry, mildew-resistant), Hinnomaki Red, Pixwell, Jostaberry (currant×gooseberry cross)", notes: "Shade tolerant. Excellent for jams, jellies, syrups.", urdu: { name: "کرینٹس اور گوزبیری", desc: "کنیکٹیکٹ کی ٹھنڈی، مرطوب آب و ہوا میں پھلتے پھولتے ہیں۔ جزوی سایہ ٹھیک ہے۔ کم کیڑوں کے مسائل۔", varieties: "ریڈ لیک، روواڈا، ٹیٹانیا (کالی، زنگ مزاحم)، پنک شیمپین، انوکٹا (گوزبیری، پھپھوندی مزاحم)، جوسٹابیری", notes: "سایہ برداشت۔ مربوں، جیلیوں، شربتوں کے لیے بہترین۔" } },
    { name: "Elderberry", diff: 1, desc: "Native shrub. MUST cook berries before eating (raw berries toxic). Immune-boosting syrups.", varieties: "Adams, York, Nova, Bob Gordon (3× yields of others)", notes: "Plant 2 for cross-pollination. Prune out 3+ year old canes.", urdu: { name: "ایلڈر بیری", desc: "مقامی جھاڑی۔ کھانے سے پہلے بیریاں ضرور پکائیں (کچی بیریاں زہریلی ہیں)۔ قوت مدافعت بڑھانے والے شربت۔", varieties: "ایڈمز، یارک، نووا، باب گورڈن (دوسروں سے 3 گنا زیادہ پیداوار)", notes: "جرگ کے لیے 2 لگائیں۔ 3+ سال پرانی شاخیں کاٹ دیں۔" } },
    { name: "Honeyberry / Haskap", diff: 1, desc: "Earliest fruit of the season — ripens 2–3 weeks before strawberries. Extremely cold-hardy (Zones 2–7).", varieties: "Borealis (best flavor), Tundra, Aurora, Boreal series (newer, larger fruit)", notes: "Need 2 compatible cultivars from different pollination groups.", urdu: { name: "ہنی بیری / ہاسکاپ", desc: "موسم کا سب سے پہلا پھل — سٹرابیری سے 2-3 ہفتے پہلے پکتا ہے۔ انتہائی سردی برداشت (زون 2-7)۔", varieties: "بوریالس (بہترین ذائقہ)، ٹنڈرا، اورورا، بوریل سیریز (نئی، بڑا پھل)", notes: "مختلف جرگ گروپوں سے 2 موافق اقسام ضروری ہیں۔" } },
    { name: "Hardy Kiwi", diff: 2, desc: "Confirmed fruiting in CT, producing fruit 3 years after planting. Grape-sized, smooth-skinned, sweet. Vines grow 30 ft/yr.", varieties: "Ananasnaya/Anna (pineapple flavor), Issai (only self-fertile cultivar), Geneva", notes: "Need strong trellis (like grapes). Need male + female plants unless using Issai.", urdu: { name: "سخت جان کیوی", desc: "کنیکٹیکٹ میں پھل دینے کی تصدیق، لگانے کے 3 سال بعد پھل۔ انگور کے سائز کا، ہموار جلد، میٹھا۔", varieties: "اناناسنایا/انا (انناس کا ذائقہ)، ایسائی (واحد خود بارور قسم)، جنیوا", notes: "مضبوط ٹریلس ضروری۔ ایسائی کے علاوہ نر + مادہ پودے ضروری۔" } },
    { name: "Serviceberry / Juneberry", diff: 1, desc: "Native ornamental with blueberry-like fruit. Beautiful spring flowers, fall color.", varieties: "Regent (compact Saskatoon type), Thiessen, native Amelanchier species", notes: "Low maintenance. Birds compete for fruit — netting helps.", urdu: { name: "سروس بیری / جون بیری", desc: "بلیو بیری جیسے پھل والا مقامی سجاوٹی درخت۔ خوبصورت بہار کے پھول، خزاں کے رنگ۔", varieties: "ریجنٹ (چھوٹا ساسکاٹون قسم)، تھیسن، مقامی ایمیلانچیئر نوعیں", notes: "کم دیکھ بھال۔ پرندے پھل کے لیے مقابلہ کرتے ہیں — جال مددگار ہے۔" } },
    { name: "Figs (with protection)", diff: 3, desc: "CT growers harvest 1,300+ figs/yr with winter wrapping. One family: in-ground fig trees for 90+ years.", varieties: "Chicago Hardy (stems hardy to 10°F, roots to -20°F, fruits on new wood), Brown Turkey, Celeste, Violette de Bordeaux", notes: "Wrap in burlap/insulation or bury under dry leaves with weighted tarp. Container growing also works.", urdu: { name: "انجیر (حفاظت کے ساتھ)", desc: "کنیکٹیکٹ کے کاشتکار سردیوں کی لپیٹ سے سالانہ 1,300+ انجیر کاٹتے ہیں۔ ایک خاندان: 90+ سال سے زمین میں انجیر کے درخت۔", varieties: "شکاگو ہارڈی (تنے 10°F تک، جڑیں -20°F تک سخت، نئی لکڑی پر پھل)، براؤن ترکی، سیلسٹ، وایولیٹ دی بورڈو", notes: "ٹاٹ/انسولیشن میں لپیٹیں یا خشک پتوں کے نیچے دبائیں۔ گملے میں اُگانا بھی کام کرتا ہے۔" } },
    { name: "Cornelian Cherry", diff: 1, desc: "Cornus mas — earliest spring bloom, virtually pest-free. Tart fruit for syrups/preserves.", varieties: "Elegant, Jolico, Pioneer (all selected for fruit quality)", notes: "Hardy Zone 4. Self-fertile but better yields with 2 plants.", urdu: { name: "کارنیلین چیری", desc: "بہار کا سب سے پہلا پھول، تقریباً کیڑوں سے پاک۔ شربتوں/مربوں کے لیے کھٹا پھل۔", varieties: "ایلیگنٹ، جولیکو، پائنیر (تمام پھل کے معیار کے لیے منتخب)", notes: "زون 4 تک سخت جان۔ خود بارور لیکن 2 پودوں سے بہتر پیداوار۔" } },
    { name: "Aronia / Chokeberry", diff: 1, desc: "Native, bulletproof. Grows in ANY soil — wet, dry, clay, poor. CT farms grow commercially.", varieties: "Viking, Nero, Autumn Magic", notes: "Astringent raw but excellent processed (juice, jam, wine). Highest antioxidants of any temperate berry.", urdu: { name: "ارونیا / چوک بیری", desc: "مقامی، ناقابل تباہ۔ کسی بھی مٹی میں اُگتی ہے — گیلی، خشک، چکنی، خراب۔ کنیکٹیکٹ کے فارم تجارتی طور پر اُگاتے ہیں۔", varieties: "وائکنگ، نیرو، آٹم میجک", notes: "کچی کسیلی لیکن پراسیس شدہ بہترین (جوس، مربہ، شراب)۔ کسی بھی معتدل بیری سے زیادہ اینٹی آکسیڈنٹس۔" } },
    { name: "Lingonberry", diff: 2, desc: "Evergreen groundcover producing tart red berries. Needs acidic soil like blueberries.", varieties: "Koralle, Red Pearl, Splendor", notes: "Low-growing (12–18 in). Slow to establish but long-lived.", urdu: { name: "لنگن بیری", desc: "سدا بہار زمینی پودا جو کھٹی سرخ بیریاں پیدا کرتا ہے۔ بلیو بیری کی طرح تیزابی مٹی ضروری۔", varieties: "کورالے، ریڈ پرل، سپلینڈر", notes: "نیچے اُگنے والا (12-18 انچ)۔ قائم ہونے میں سست لیکن لمبی عمر۔" } },
    { name: "Beach Plum", diff: 2, desc: "Native coastal species that grows inland with well-drained soil. Exceptional jam.", varieties: "Seedling selections (few named cultivars available)", notes: "Zones 3–7. Very ornamental. Plant several for cross-pollination.", urdu: { name: "بیچ پلم", desc: "مقامی ساحلی نوع جو اچھی نکاسی والی مٹی میں اندرون ملک اُگتی ہے۔ لاجواب مربہ۔", varieties: "پودوں کے انتخاب (چند نامزد اقسام دستیاب)", notes: "زون 3-7۔ بہت سجاوٹی۔ جرگ کے لیے کئی لگائیں۔" } },
    { name: "Goji Berry", diff: 2, desc: "Lycium barbarum. Hardy to Zone 5, self-fertile, drought-tolerant once established.", varieties: "Crimson Star, Phoenix Tears, Sweet Lifeberry", notes: "Grows readily in Zone 6. Can be invasive via suckers — contain or manage. Berries ripen mid-summer.", urdu: { name: "گوجی بیری", desc: "زون 5 تک سخت جان، خود بارور، قائم ہونے کے بعد خشک سالی برداشت۔", varieties: "کرمسن سٹار، فینکس ٹیئرز، سویٹ لائف بیری", notes: "زون 6 میں آسانی سے اُگتی ہے۔ شاخوں سے پھیل سکتی ہے — قابو میں رکھیں۔ بیریاں وسط گرما میں پکتی ہیں۔" } },
    { name: "Goumi", diff: 2, desc: "Elaeagnus multiflora. Nitrogen-fixing shrub with sweet-tart berries. Hardy to Zone 4.", varieties: "Sweet Scarlet (largest fruit), Red Gem", notes: "Self-fertile but better yields with 2. Fixes nitrogen — improves surrounding soil. Few pest issues.", urdu: { name: "گومی", desc: "نائٹروجن فکس کرنے والی جھاڑی جس کی میٹھی کھٹی بیریاں ہوتی ہیں۔ زون 4 تک سخت جان۔", varieties: "سویٹ سکارلٹ (سب سے بڑا پھل)، ریڈ جیم", notes: "خود بارور لیکن 2 سے بہتر پیداوار۔ نائٹروجن فکس — ارد گرد کی مٹی بہتر کرتی ہے۔" } },
    { name: "Wineberry", diff: 1, desc: "Rubus phoenicolasius. Beautiful red-stemmed raspberry relative. Produces sweet, jewel-like berries.", varieties: "Wild type (no named cultivars — all are excellent)", notes: "Considered invasive in some states — check local regulations. Self-fertile, spreads readily.", urdu: { name: "وائن بیری", desc: "خوبصورت سرخ تنے والی رس بھری کی رشتہ دار۔ میٹھی، جواہر جیسی بیریاں پیدا کرتی ہے۔", varieties: "جنگلی قسم (کوئی نامزد اقسام نہیں — سب بہترین ہیں)", notes: "بعض ریاستوں میں ناگوار سمجھی جاتی ہے — مقامی ضوابط چیک کریں۔ خود بارور، آسانی سے پھیلتی ہے۔" } },
  ]},
  { category: "Warm-Season Vegetables", icon: "🍅", color: "#D35400", bg: "#FDF2E9", items: [
    { name: "Tomatoes", diff: 1, desc: "CT's most popular garden crop. Start indoors 6–8 weeks before transplant (late March).", varieties: "Early Girl, Sungold (must-grow cherry), Celebrity (VFN resistant), Big Beef (VFFNTA), Mountain Merit (late blight resistant), Cherokee Purple, Brandywine, Black Krim, San Marzano, Juliet (crack-resistant grape), Amish Paste", notes: "Sungold universally called 'must-grow' by CT gardeners. Mountain Merit essential for humid summers.", urdu: { name: "ٹماٹر", desc: "کنیکٹیکٹ کی سب سے مقبول باغبانی فصل۔ منتقلی سے 6-8 ہفتے پہلے اندر شروع کریں (مارچ کے آخر میں)۔", varieties: "ارلی گرل، سن گولڈ (ضرور اُگائیں)، سیلیبرٹی، بگ بیف، ماؤنٹین میرٹ (لیٹ بلائٹ مزاحم)، چیروکی پرپل، برینڈی وائن، سان مارزانو، جولیٹ", notes: "سن گولڈ کو کنیکٹیکٹ کے باغبانوں نے عالمگیر طور پر 'ضرور اُگائیں' کہا ہے۔ نمی والی گرمیوں کے لیے ماؤنٹین میرٹ ضروری۔" } },
    { name: "Peppers (Sweet)", diff: 2, desc: "More challenging than tomatoes — cool nights slow them. Black plastic mulch helps significantly.", varieties: "King of the North (#1 for NE, bred for short seasons/cool weather), Ace (fastest bell, 50–60d), Carmen (AAS winner Italian frying), Jimmy Nardello (prolific heirloom), California Wonder", notes: "Start indoors 8–10 weeks before transplant. Row covers extend season.", urdu: { name: "شملہ مرچ (میٹھی)", desc: "ٹماٹروں سے زیادہ مشکل — ٹھنڈی راتیں انہیں سست کر دیتی ہیں۔ سیاہ پلاسٹک ملچ نمایاں مدد کرتا ہے۔", varieties: "کنگ آف دی نارتھ (شمال مشرق کے لیے #1)، ایس (تیز ترین بیل)، کارمن (AAS فاتح)، جمی نارڈیلو، کیلیفورنیا ونڈر", notes: "منتقلی سے 8-10 ہفتے پہلے اندر شروع کریں۔ قطار ڈھانپنے سے موسم بڑھتا ہے۔" } },
    { name: "Peppers (Hot)", diff: 2, desc: "Short-season varieties essential. Habanero (90–100d) is a stretch — start very early.", varieties: "Early Jalapeño (65d), Hungarian Hot Wax (58–65d, excellent short-season), Cayenne, Serrano, Habanero (challenge crop)", notes: "Containers work well for hot peppers. Start indoors 8–10 weeks early.", urdu: { name: "مرچ (تیز)", desc: "مختصر موسم کی اقسام ضروری۔ ہبانیرو (90-100 دن) مشکل ہے — بہت جلدی شروع کریں۔", varieties: "ارلی ہالاپینو (65 دن)، ہنگیرین ہاٹ ویکس (58-65 دن)، لال مرچ، سیرانو، ہبانیرو (چیلنج فصل)", notes: "گملے تیز مرچوں کے لیے اچھے ہیں۔ 8-10 ہفتے پہلے اندر شروع کریں۔" } },
    { name: "Zucchini / Summer Squash", diff: 1, desc: "Prolific. Succession-plant June + early July to dodge squash vine borers.", varieties: "Dunja (powdery mildew resistant, CT pick), Costata Romanesco (superior flavor), Yellow Crookneck, Sunburst pattypan", notes: "Vine borer defense: row covers until flowering, or late July planting dodges borer moths.", urdu: { name: "توری / گرمائی کدو", desc: "بے حد پیداواری۔ تنے کے سنڈیوں سے بچنے کے لیے جون + ابتدائی جولائی میں یکے بعد دیگرے لگائیں۔", varieties: "ڈنجا (پاؤڈری پھپھوندی مزاحم)، کوسٹاٹا رومانیسکو (بہترین ذائقہ)، زرد کروکنیک، سن برسٹ", notes: "تنے کے سنڈی سے بچاؤ: پھول آنے تک قطار ڈھانپنا، یا دیر جولائی کی بوائی۔" } },
    { name: "Winter Squash", diff: 2, desc: "Butternut types have dense stems that naturally resist vine borers — major advantage.", varieties: "Waltham Butternut (standard), Honeynut (intense sweetness, mini), Delicata (edible skin), Table Queen acorn (80–85d), Red Kuri/Kabocha, Tromboncino (borer-immune Italian)", notes: "Butternut/Tromboncino = best vine borer defense. Blue Hubbard tight at 100–120d.", urdu: { name: "سردیوں کا کدو", desc: "بٹرنٹ اقسام کے گھنے تنے قدرتی طور پر تنے کے سنڈیوں کا مقابلہ کرتے ہیں — بڑا فائدہ۔", varieties: "والتھم بٹرنٹ (معیاری)، ہنی نٹ (شدید مٹھاس، چھوٹا)، ڈیلیکاٹا (کھانے کے قابل چھلکا)، ریڈ کوری/کابوچا، ٹرومبونسینو (سنڈی مزاحم)", notes: "بٹرنٹ/ٹرومبونسینو = بہترین تنے کے سنڈی دفاع۔" } },
    { name: "Pumpkins", diff: 1, desc: "Heritage Connecticut crop. Direct sow late May to early June.", varieties: "Connecticut Field (the classic), Howden (bred in CT, standard jack-o'-lantern), Sugar Pie, New England Pie", notes: "Need space (vines spread 15–20 ft). Semi-bush varieties for small gardens.", urdu: { name: "کدو", desc: "کنیکٹیکٹ کی روایتی فصل۔ مئی کے آخر سے جون کے شروع میں براہ راست بوائی۔", varieties: "کنیکٹیکٹ فیلڈ (کلاسک)، ہاؤڈن (CT میں تیار)، شوگر پائی، نیو انگلینڈ پائی", notes: "جگہ چاہیے (بیلیں 15-20 فٹ پھیلتی ہیں)۔ چھوٹے باغوں کے لیے نیم جھاڑی اقسام۔" } },
    { name: "Cucumbers", diff: 1, desc: "Direct sow after frost or start indoors 3–4 weeks early.", varieties: "Marketmore 76 (disease-resistant slicer), Northern Pickling (very short season, CT recommended), Diva (seedless, parthenocarpic)", notes: "Cucumber beetles transmit bacterial wilt — row covers until flowering = primary defense.", urdu: { name: "کھیرا", desc: "پالے کے بعد براہ راست بوائی یا 3-4 ہفتے پہلے اندر شروع کریں۔", varieties: "مارکیٹ مور 76 (بیماری مزاحم)، ناردرن پکلنگ (بہت مختصر موسم)، ڈیوا (بیج کے بغیر)", notes: "کھیرے کے بھونگے بیکٹیریل مرجھانا پھیلاتے ہیں — پھول آنے تک قطار ڈھانپنا = اولین دفاع۔" } },
    { name: "Sweet Corn", diff: 2, desc: "Plant in blocks (not rows) for pollination. Raccoon fencing often needed in CT.", varieties: "Temptation (69d bicolor), Peaches & Cream, Butter & Sugar, Incredible, Silver Queen (92d — tight, needs early planting)", notes: "Direct sow after soil reaches 60°F. Needs space — not ideal for small gardens.", urdu: { name: "میٹھی مکئی", desc: "جرگ کے لیے قطاروں کی بجائے بلاکوں میں لگائیں۔ کنیکٹیکٹ میں ریکون فینسنگ اکثر ضروری۔", varieties: "ٹمپٹیشن (69 دن)، پیچز اینڈ کریم، بٹر اینڈ شوگر، انکریڈبل، سلور کوئین (92 دن — جلدی لگائیں)", notes: "مٹی 60°F پہنچنے کے بعد براہ راست بوائی۔ جگہ چاہیے — چھوٹے باغوں کے لیے مثالی نہیں۔" } },
    { name: "Beans (Snap/Pole)", diff: 1, desc: "Direct sow after last frost. One of the easiest warm-season crops.", varieties: "Provider (cold-soil tolerant, earliest), Blue Lake 274 (classic flavor), Contender, Kentucky Wonder (pole), Fortex (pole, long French filet)", notes: "Provider and Contender germinate in cooler soil than other beans.", urdu: { name: "پھلیاں (سنیپ/پول)", desc: "آخری پالے کے بعد براہ راست بوائی۔ سب سے آسان گرم موسمی فصلوں میں سے ایک۔", varieties: "پرووائیڈر (ٹھنڈی مٹی برداشت)، بلیو لیک 274 (کلاسک ذائقہ)، کنٹینڈر، کینٹکی ونڈر (پول)، فورٹیکس", notes: "پرووائیڈر اور کنٹینڈر دوسری پھلیوں سے ٹھنڈی مٹی میں اُگتے ہیں۔" } },
    { name: "Beans (Lima/Edamame)", diff: 2, desc: "Need warmer soil than snap beans. Bush limas more reliable for CT than pole types.", varieties: "Fordhook 242 (bush lima, more reliable for CT), Midori Giant edamame (75–90d)", notes: "Wait until soil is 65°F+. Edamame surprisingly productive in Zone 6b.", urdu: { name: "پھلیاں (لیما/ایڈامامے)", desc: "سنیپ پھلیوں سے گرم مٹی چاہیے۔ جھاڑی والی لیما کنیکٹیکٹ کے لیے زیادہ قابل اعتماد۔", varieties: "فورڈہک 242 (جھاڑی لیما)، میڈوری جائنٹ ایڈامامے (75-90 دن)", notes: "مٹی 65°F+ ہونے تک انتظار کریں۔ ایڈامامے حیرت انگیز طور پر زون 6b میں پیداواری۔" } },
    { name: "Melons (Cantaloupe)", diff: 3, desc: "Possible but demanding. Black plastic + transplants + row covers are mandatory, not optional.", varieties: "Minnesota Midget (68d), Halona (bred at UNH for NE, disease-resistant), Sugar Cube", notes: "Choose varieties under 80 days. IRT mulch film helps. Start indoors 3–4 weeks early.", urdu: { name: "خربوزہ", desc: "ممکن لیکن مشکل۔ سیاہ پلاسٹک + پودے + قطار ڈھانپنا لازمی ہے، اختیاری نہیں۔", varieties: "مینیسوٹا مجیٹ (68 دن)، ہالونا (نیو انگلینڈ کے لیے تیار، بیماری مزاحم)، شوگر کیوب", notes: "80 دن سے کم کی اقسام چنیں۔ 3-4 ہفتے پہلے اندر شروع کریں۔" } },
    { name: "Watermelon", diff: 3, desc: "Icebox types (small) most reliable. Same season-extension treatment as cantaloupe.", varieties: "Blacktail Mountain (70d, developed for 75-day seasons), Sugar Baby, New Hampshire Midget", notes: "Blacktail Mountain developed for short-season areas — best bet for CT.", urdu: { name: "تربوز", desc: "آئس باکس اقسام (چھوٹے) سب سے زیادہ قابل اعتماد۔ خربوزے جیسا موسم بڑھانے کا طریقہ۔", varieties: "بلیکٹیل ماؤنٹین (70 دن، مختصر موسم کے لیے تیار)، شوگر بیبی، نیو ہیمپشائر مجیٹ", notes: "بلیکٹیل ماؤنٹین مختصر موسم والے علاقوں کے لیے تیار — کنیکٹیکٹ کے لیے بہترین انتخاب۔" } },
    { name: "Eggplant", diff: 2, desc: "Loves heat. Black plastic mulch essential. Asian/mini types mature faster.", varieties: "Orient Express (58–65d, best short-season), Fairy Tale (50–65d, mini, heavy yields), Nadia (67d), Black Beauty", notes: "Start indoors 8–10 weeks. Flea beetles are main pest — row covers help.", urdu: { name: "بینگن", desc: "گرمی سے محبت کرتا ہے۔ سیاہ پلاسٹک ملچ ضروری۔ ایشیائی/چھوٹی اقسام تیزی سے پکتی ہیں۔", varieties: "اورینٹ ایکسپریس (58-65 دن، بہترین مختصر موسم)، فیری ٹیل (50-65 دن، چھوٹا، بھاری پیداوار)، نادیا، بلیک بیوٹی", notes: "8-10 ہفتے اندر شروع کریں۔ پسو بھونگے اصل کیڑے ہیں — قطار ڈھانپنا مددگار۔" } },
    { name: "Sweet Potatoes", diff: 3, desc: "Yes, they work in CT! Black plastic mulch essential for soil warming.", varieties: "Beauregard (best yields in MOFGA NE trials), Georgia Jet (80–90d, earliest), Covington", notes: "Plant slips after soil is thoroughly warm (late May/June). Cure at 80–85°F after harvest.", urdu: { name: "شکرقندی", desc: "ہاں، یہ کنیکٹیکٹ میں کام کرتے ہیں! مٹی گرم کرنے کے لیے سیاہ پلاسٹک ملچ ضروری۔", varieties: "بیوریگارڈ (نیو انگلینڈ ٹرائلز میں بہترین پیداوار)، جارجیا جیٹ (80-90 دن، سب سے پہلے)، کووِنگٹن", notes: "مٹی اچھی طرح گرم ہونے کے بعد پودے لگائیں (مئی/جون کے آخر میں)۔ فصل کے بعد 80-85°F پر خشک کریں۔" } },
    { name: "Potatoes", diff: 1, desc: "Love CT's naturally acidic soil. Plant mid-April, 2–3 weeks before last frost.", varieties: "Yukon Gold, Kennebec (late blight resistant NE classic), Red Norland (early), Katahdin (excellent storage), Adirondack Blue", notes: "Hill soil around stems as they grow. Kennebec has good late blight resistance.", urdu: { name: "آلو", desc: "کنیکٹیکٹ کی قدرتی تیزابی مٹی سے محبت کرتے ہیں۔ اپریل کے وسط میں، آخری پالے سے 2-3 ہفتے پہلے لگائیں۔", varieties: "یوکون گولڈ، کینیبیک (لیٹ بلائٹ مزاحم)، ریڈ نورلینڈ (ابتدائی)، کاٹاہڈن (بہترین ذخیرہ)، ایڈیرانڈیک بلیو", notes: "بڑھنے کے ساتھ تنوں کے ارد گرد مٹی چڑھائیں۔ کینیبیک کی اچھی لیٹ بلائٹ مزاحمت ہے۔" } },
    { name: "Okra", diff: 3, desc: "Marginal for CT but doable with earliest varieties and full sun. Heat lover.", varieties: "Cajun Delight (50–55d), Annie Oakley II (50–55d)", notes: "Start indoors. Black plastic mulch. Choose ONLY 50–55 day varieties.", urdu: { name: "بھنڈی", desc: "کنیکٹیکٹ کے لیے کم عملی لیکن ابتدائی اقسام اور پوری دھوپ کے ساتھ ممکن۔ گرمی پسند۔", varieties: "کیجن ڈیلائٹ (50-55 دن)، اینی اوکلے II (50-55 دن)", notes: "اندر شروع کریں۔ سیاہ پلاسٹک ملچ۔ صرف 50-55 دن کی اقسام چنیں۔" } },
    { name: "Ground Cherries", diff: 1, desc: "Sweet tropical-flavored fruit in paper husks. Self-sowing annual. Kids love them.", varieties: "Aunt Molly's (standard, excellent flavor)", notes: "Prolific. Fruit drops when ripe — harvest from ground. Will self-sow.", urdu: { name: "رس بھری (زمینی)", desc: "کاغذی خول میں میٹھا اشنکٹبندیی ذائقے والا پھل۔ خود بیج بونے والا سالانہ۔ بچے انہیں پسند کرتے ہیں۔", varieties: "آنٹ مولی (معیاری، بہترین ذائقہ)", notes: "بے حد پیداواری۔ پکنے پر پھل گر جاتا ہے — زمین سے چنیں۔ خود بیج بوئے گا۔" } },
    { name: "Tomatillos", diff: 1, desc: "Prolific salsa verde staple. Need 2+ plants for pollination.", varieties: "Toma Verde (standard green), Purple tomatillo", notes: "Cross-pollinate: plant at least 2. Very vigorous — give space.", urdu: { name: "ٹوماٹیلو", desc: "سالسا وردے کا اہم جزو۔ جرگ کے لیے 2+ پودے ضروری۔", varieties: "ٹوما وردے (معیاری سبز)، جامنی ٹوماٹیلو", notes: "جرگ: کم از کم 2 لگائیں۔ بہت توانا — جگہ دیں۔" } },
  ]},
  { category: "Cool-Season Vegetables", icon: "🥬", color: "#1E8449", bg: "#EAFAF1", items: [
    { name: "Lettuce", diff: 1, desc: "Two windows: spring (April–May) and fall (Aug–Sept sow). Shade cloth in summer prevents bolting.", varieties: "Jericho (heat-tolerant romaine), Winter Density (cold-hardy), Buttercrunch (heat-tolerant butterhead), Red Sails, Black Seeded Simpson", notes: "Succession-sow every 2 weeks. Row cover extends fall harvest into December.", urdu: { name: "سلاد پتہ", desc: "دو موقعے: بہار (اپریل-مئی) اور خزاں (اگست-ستمبر بوائی)۔ گرمیوں میں سایہ بان بولٹنگ روکتا ہے۔", varieties: "جیریکو (گرمی برداشت رومین)، ونٹر ڈینسٹی (سردی برداشت)، بٹر کرنچ، ریڈ سیلز، بلیک سیڈڈ سمپسن", notes: "ہر 2 ہفتے بوائی کریں۔ قطار ڈھانپنے سے خزاں کی فصل دسمبر تک بڑھتی ہے۔" } },
    { name: "Spinach", diff: 1, desc: "Best spring and fall — bolts above 75°F. Direct sow as soon as soil is workable.", varieties: "Bloomsdale Long Standing, Space (CT recommended), Tyee (excellent bolt resistance)", notes: "Fall spinach (sow late Aug) is often better quality than spring.", urdu: { name: "پالک", desc: "بہار اور خزاں میں بہترین — 75°F سے اوپر بیج بنا لیتا ہے۔ مٹی کام کرنے لائق ہوتے ہی بوائی کریں۔", varieties: "بلومزڈیل لانگ سٹینڈنگ، سپیس (CT تجویز)، ٹائی (بہترین بولٹ مزاحمت)", notes: "خزاں کا پالک (اگست کے آخر میں بوائی) اکثر بہار سے بہتر معیار کا ہوتا ہے۔" } },
    { name: "Kale", diff: 1, desc: "Sweetens dramatically after frost. Harvest through December with row cover.", varieties: "Winterbor (extremely cold-hardy, CT recommended), Lacinato/Dinosaur (sweetest after frost), Red Russian", notes: "Start June for fall/winter harvest. Can overwinter under snow for early spring harvest.", urdu: { name: "کیل", desc: "پالے کے بعد نمایاں طور پر میٹھا ہو جاتا ہے۔ قطار ڈھانپنے سے دسمبر تک فصل۔", varieties: "ونٹربور (انتہائی سردی برداشت)، لاسیناٹو/ڈائنوسار (پالے کے بعد سب سے میٹھا)، ریڈ رشین", notes: "خزاں/سردیوں کی فصل کے لیے جون میں شروع کریں۔ برف کے نیچے سردیاں گزار سکتا ہے۔" } },
    { name: "Swiss Chard", diff: 1, desc: "Both heat and cold tolerant — one of the longest-producing greens (spring through fall).", varieties: "Bright Lights (ornamental multicolor), Fordhook Giant", notes: "Cut-and-come-again harvest. Ornamental enough for flower borders.", urdu: { name: "سوئس چارڈ", desc: "گرمی اور سردی دونوں برداشت — سب سے لمبی پیداوار والی سبزیوں میں سے (بہار سے خزاں)۔", varieties: "برائٹ لائٹس (سجاوٹی رنگین)، فورڈہک جائنٹ", notes: "کاٹو اور دوبارہ اُگنے دو فصل۔ پھولوں کی بارڈرز کے لیے کافی سجاوٹی۔" } },
    { name: "Broccoli", diff: 2, desc: "Better as fall crop in CT (spring plantings bolt). Choose side-shoot types for extended harvest.", varieties: "DeCicco (many side shoots), Green Magic (early), Waltham 29 (bred for NE fall production)", notes: "Row cover deters cabbage worms. Start indoors March (spring) or June (fall).", urdu: { name: "بروکولی", desc: "کنیکٹیکٹ میں خزاں کی فصل بہتر (بہار کی کاشت بولٹ کرتی ہے)۔ لمبی فصل کے لیے سائیڈ شوٹ اقسام چنیں۔", varieties: "ڈی سیکو (بہت سے سائیڈ شوٹ)، گرین میجک (ابتدائی)، والتھم 29 (شمال مشرق خزاں کے لیے تیار)", notes: "قطار ڈھانپنا بند گوبھی کے کیڑوں کو روکتا ہے۔ مارچ (بہار) یا جون (خزاں) میں اندر شروع کریں۔" } },
    { name: "Cauliflower", diff: 3, desc: "Fussiest brassica. Needs consistent moisture and moderate temps. Fall crop more reliable.", varieties: "Snow Crown (reliable NE hybrid), Amazing (self-blanching)", notes: "Self-blanching varieties save work. Heads must be shielded from sun to stay white.", urdu: { name: "پھول گوبھی", desc: "سب سے نازک گوبھی۔ مستقل نمی اور معتدل درجہ حرارت چاہیے۔ خزاں کی فصل زیادہ قابل اعتماد۔", varieties: "سنو کراؤن (قابل اعتماد NE ہائبرڈ)، امیزنگ (خود بلانچنگ)", notes: "خود بلانچنگ اقسام کام بچاتی ہیں۔ سفید رکھنے کے لیے سروں کو دھوپ سے بچائیں۔" } },
    { name: "Cabbage", diff: 1, desc: "Reliable spring and fall. Storage varieties keep months in cold storage.", varieties: "Stonehead (compact, split-resistant, CT pick), Early Jersey Wakefield, Danish Ballhead (stores 4–6 months), Savoy Ace", notes: "Danish Ballhead stores 4–6 months in root cellar.", urdu: { name: "بند گوبھی", desc: "بہار اور خزاں میں قابل اعتماد۔ ذخیرے کی اقسام مہینوں ٹھنڈے ذخیرے میں رہتی ہیں۔", varieties: "اسٹون ہیڈ (چھوٹا، پھٹنے مزاحم)، ارلی جرسی ویکفیلڈ، ڈینش بال ہیڈ (4-6 ماہ ذخیرہ)، سیوائے ایس", notes: "ڈینش بال ہیڈ تہہ خانے میں 4-6 ماہ محفوظ رہتا ہے۔" } },
    { name: "Brussels Sprouts", diff: 2, desc: "Frost dramatically sweetens them. Start May–June for Oct–Nov harvest.", varieties: "Jade Cross, Diablo, Long Island Improved", notes: "Remove lower leaves as sprouts develop. Top the plant in Sept to size up sprouts.", urdu: { name: "برسلز سپراؤٹس", desc: "پالا انہیں نمایاں طور پر میٹھا کر دیتا ہے۔ اکتوبر-نومبر کی فصل کے لیے مئی-جون میں شروع کریں۔", varieties: "جیڈ کراس، ڈیابلو، لانگ آئلینڈ امپروود", notes: "سپراؤٹس بڑھنے کے ساتھ نچلے پتے ہٹا دیں۔ ستمبر میں پودے کی چوٹی کاٹیں۔" } },
    { name: "Peas", diff: 1, desc: "Among the earliest crops — direct seed late March when soil is workable.", varieties: "Sugar Snap (original, tall), Super Sugar Snap (disease-resistant), Oregon Sugar Pod (dwarf snow), Lincoln (shelling)", notes: "Inoculate with rhizobium. Provide trellis. Stop producing in summer heat.", urdu: { name: "مٹر", desc: "سب سے پہلی فصلوں میں — مارچ کے آخر میں براہ راست بیج بوئیں جب مٹی کام کرنے لائق ہو۔", varieties: "شوگر سنیپ (اصلی، لمبا)، سپر شوگر سنیپ (بیماری مزاحم)، اوریگون شوگر پوڈ (بونا)، لنکن (چھیلنے والا)", notes: "رائزوبیم سے ٹیکہ لگائیں۔ ٹریلس فراہم کریں۔ گرمی کی شدت میں پیداوار بند ہو جاتی ہے۔" } },
    { name: "Carrots", diff: 2, desc: "For CT's rocky soil, choose short/blunt types. Raised beds solve rock problems.", varieties: "Danvers Half Long (bred for hard NE soils!), Chantenay (short, 4–5 in), Bolero (storage), Napoli, Yaya, Thumbelina (round, stony ground OK)", notes: "Danvers was literally bred for New England's stony soils. Thin seedlings to 2 in.", urdu: { name: "گاجر", desc: "کنیکٹیکٹ کی پتھریلی مٹی کے لیے مختصر/کُند اقسام چنیں۔ اُٹھے ہوئے بستر پتھر کا مسئلہ حل کرتے ہیں۔", varieties: "ڈینورز ہاف لانگ (نیو انگلینڈ کی سخت مٹی کے لیے تیار!)، شانتے نے (مختصر)، بولیرو (ذخیرہ)، تھمبلینا (گول، پتھریلی زمین ٹھیک)", notes: "ڈینورز لفظی طور پر نیو انگلینڈ کی پتھریلی مٹی کے لیے تیار کیا گیا۔ پودوں کو 2 انچ تک پتلا کریں۔" } },
    { name: "Beets", diff: 1, desc: "Easy dual-purpose — eat both roots and greens.", varieties: "Detroit Dark Red, Chioggia (candy-striped), Touchstone Gold, Cylindra (uniform slices)", notes: "Soak seeds overnight. Each 'seed' is a cluster — thin early.", urdu: { name: "چقندر", desc: "آسان دوہرے مقصد — جڑیں اور پتے دونوں کھائیں۔", varieties: "ڈیٹرائٹ ڈارک ریڈ، چیوجیا (دھاری دار)، ٹچ سٹون گولڈ، سلنڈرا (یکساں ٹکڑے)", notes: "بیج رات بھر بھگو دیں۔ ہر 'بیج' ایک جھرمٹ ہے — جلدی پتلا کریں۔" } },
    { name: "Radishes", diff: 1, desc: "Fastest crop in the garden — spring types ready in 22–30 days.", varieties: "Cherry Belle (22d), French Breakfast, Daikon (fall/winter), Watermelon radish (fall)", notes: "Winter types sow late July–Aug. Spring types bolt in heat.", urdu: { name: "مولی", desc: "باغ میں سب سے تیز فصل — بہار کی اقسام 22-30 دنوں میں تیار۔", varieties: "چیری بیلی (22 دن)، فرنچ بریکفاسٹ، ڈائکون (خزاں/سردی)، واٹرمیلن مولی (خزاں)", notes: "سردیوں کی اقسام جولائی-اگست کے آخر میں بوئیں۔ بہار کی اقسام گرمی میں بولٹ کرتی ہیں۔" } },
    { name: "Turnips", diff: 1, desc: "Japanese salad turnips are a revelation — sweet, crisp, eat raw.", varieties: "Hakurei (incredibly sweet, 35d — highly recommended), Purple Top White Globe (storage)", notes: "Succession sow spring and fall. Hakurei turnips are transformative.", urdu: { name: "شلجم", desc: "جاپانی سلاد شلجم حیرت انگیز ہیں — میٹھے، کرکرے، کچے کھائیں۔", varieties: "ہاکوری (ناقابل یقین حد تک میٹھا، 35 دن — انتہائی تجویز کردہ)، پرپل ٹاپ وائٹ گلوب (ذخیرہ)", notes: "بہار اور خزاں میں یکے بعد دیگرے بوائی کریں۔ ہاکوری شلجم زندگی بدل دیتے ہیں۔" } },
    { name: "Rutabaga", diff: 1, desc: "Hardier and larger than turnips. Frost converts starch to sugar. Excellent winter storage crop.", varieties: "American Purple Top (classic, 90d), Laurentian", notes: "Can overwinter in ground with mulch. Stores months in root cellar. Sow mid-summer for fall harvest.", urdu: { name: "روٹاباگا", desc: "شلجم سے زیادہ سخت جان اور بڑا۔ پالا نشاستے کو شکر میں بدلتا ہے۔ بہترین سردیوں کی ذخیرہ فصل۔", varieties: "امریکن پرپل ٹاپ (کلاسک، 90 دن)، لارینشین", notes: "ملچ کے ساتھ زمین میں سردیاں گزار سکتا ہے۔ تہہ خانے میں مہینوں محفوظ۔ وسط گرما میں بوائی۔" } },
    { name: "Parsnips", diff: 2, desc: "Slow (120d) but frost converts starch to sugar. Can overwinter in ground under mulch.", varieties: "Hollow Crown (standard), All American", notes: "Sow early spring for fall harvest. Leave in ground through frost for sweetest flavor.", urdu: { name: "پارسنپ", desc: "سست (120 دن) لیکن پالا نشاستے کو شکر میں بدلتا ہے۔ ملچ کے نیچے زمین میں سردیاں گزار سکتا ہے۔", varieties: "ہولو کراؤن (معیاری)، آل امریکن", notes: "خزاں کی فصل کے لیے ابتدائی بہار میں بوائی۔ سب سے میٹھے ذائقے کے لیے پالے میں زمین میں چھوڑ دیں۔" } },
    { name: "Onions", diff: 2, desc: "Must use LONG-DAY varieties in the Northeast. Start seeds indoors January–February.", varieties: "Copra (8–10 month storage!), Patterson (excellent storage), Walla Walla (sweet, short storage), Ailsa Craig (exhibition size). Shallots: French Grey (fall-planted sets), Zebrune (from seed)", notes: "Storage onions are the real payoff — Copra/Patterson keep nearly a year. Shallots: plant sets in fall or start Zebrune from seed.", urdu: { name: "پیاز", desc: "شمال مشرق میں صرف لانگ ڈے اقسام استعمال کریں۔ جنوری-فروری میں اندر بیج شروع کریں۔", varieties: "کوپرا (8-10 ماہ ذخیرہ!)، پیٹرسن (بہترین ذخیرہ)، والا والا (میٹھا، مختصر ذخیرہ)۔ چھوٹا پیاز: فرنچ گرے، زیبرون", notes: "ذخیرے کے پیاز اصل فائدہ ہیں — کوپرا/پیٹرسن تقریباً ایک سال رہتے ہیں۔" } },
    { name: "Garlic", diff: 1, desc: "HARDNECK types excel because CT winters provide essential cold vernalization. Plant mid-October.", varieties: "Music (porcelain, #1 Zone 6 pick), German Extra Hardy, Georgian Crystal, Chesnok Red (superb roasted), Spanish Roja", notes: "Fall-planted. Remove scapes in June for larger bulbs. Harvest when lower leaves brown.", urdu: { name: "لہسن", desc: "ہارڈنیک اقسام بہترین ہیں کیونکہ کنیکٹیکٹ کی سردیاں ضروری ٹھنڈک فراہم کرتی ہیں۔ وسط اکتوبر میں لگائیں۔", varieties: "میوزک (پورسلین، زون 6 کا #1 انتخاب)، جرمن ایکسٹرا ہارڈی، جارجین کرسٹل، چیسناک ریڈ (بھنی ہوئی بہترین)، سپینش روخا", notes: "خزاں میں لگایا جاتا ہے۔ بڑے بلب کے لیے جون میں تنے ہٹائیں۔ نچلے پتے بھورے ہونے پر کاٹیں۔" } },
    { name: "Leeks", diff: 2, desc: "Slow but rewarding. Cold-hardy varieties stand through early winter.", varieties: "King Richard (summer), Bandit (very cold-hardy for fall/winter harvest)", notes: "Start indoors Feb. Hill soil around stems for longer white shanks.", urdu: { name: "لیک", desc: "سست لیکن فائدہ مند۔ سردی برداشت اقسام ابتدائی سردیوں تک کھڑی رہتی ہیں۔", varieties: "کنگ رچرڈ (گرمائی)، بینڈٹ (خزاں/سردیوں کی فصل کے لیے بہت سردی برداشت)", notes: "فروری میں اندر شروع کریں۔ لمبے سفید تنوں کے لیے تنوں کے ارد گرد مٹی چڑھائیں۔" } },
    { name: "Kohlrabi", diff: 1, desc: "Quick, cold-tolerant, underrated. Mild, crunchy, apple-like texture.", varieties: "Early White Vienna (55d), Kolibri (purple)", notes: "Harvest tennis-ball sized. Larger ones get woody. Very fast crop.", urdu: { name: "کول رابی / گانٹھ گوبھی", desc: "تیز، سردی برداشت، کم قدر۔ ہلکا، کرکرا، سیب جیسی ساخت۔", varieties: "ارلی وائٹ ویانا (55 دن)، کولیبری (جامنی)", notes: "ٹینس بال کے سائز پر کاٹیں۔ بڑے والے لکڑی والے ہو جاتے ہیں۔ بہت تیز فصل۔" } },
    { name: "Asian Greens", diff: 1, desc: "Superb fall crops. Some of the most cold-tolerant greens available.", varieties: "Mei Qing baby bok choy (40–50d), Mizuna (mild, 35d), Tatsoi (survives 10–20°F), Napa cabbage (fall-sow ONLY — spring bolts)", notes: "Sow late July–Aug for fall. Tatsoi is remarkably cold-hardy.", urdu: { name: "ایشیائی ساگ", desc: "شاندار خزاں کی فصلیں۔ دستیاب سب سے زیادہ سردی برداشت سبزیوں میں سے۔", varieties: "میئی چنگ بیبی بوک چوائے (40-50 دن)، مزونا (ہلکا، 35 دن)، ٹاٹسوائے (10-20°F تک زندہ رہتا ہے)، ناپا گوبھی (صرف خزاں میں بوئیں)", notes: "خزاں کے لیے جولائی-اگست کے آخر میں بوئیں۔ ٹاٹسوائے حیرت انگیز طور پر سردی برداشت ہے۔" } },
    { name: "Radicchio / Endive", diff: 2, desc: "Excellent fall crops that sweeten with frost.", varieties: "Radicchio di Chioggia, Sugarloaf endive, Batavian escarole", notes: "Sow July for fall harvest. Frost improves flavor significantly.", urdu: { name: "ریڈیکیو / اینڈائیو", desc: "بہترین خزاں کی فصلیں جو پالے سے میٹھی ہو جاتی ہیں۔", varieties: "ریڈیکیو ڈی چیوجیا، شوگرلوف اینڈائیو، بیٹیویئن ایسکارول", notes: "خزاں کی فصل کے لیے جولائی میں بوئیں۔ پالا ذائقے کو نمایاں طور پر بہتر کرتا ہے۔" } },
    { name: "Mache / Corn Salad", diff: 1, desc: "One of the most cold-hardy salad greens. Survives well below freezing under row cover.", varieties: "Vit (standard), Large Seeded", notes: "Sow late Aug-Sept for fall/winter harvest. Excellent in cold frames. Nutty, mild flavor.", urdu: { name: "ماشے / کارن سلاد", desc: "سب سے زیادہ سردی برداشت سلاد سبزیوں میں سے۔ قطار ڈھانپنے کے نیچے جمنے سے کافی نیچے تک زندہ رہتا ہے۔", varieties: "وٹ (معیاری)، بڑے بیج والا", notes: "خزاں/سردیوں کی فصل کے لیے اگست-ستمبر کے آخر میں بوئیں۔ ٹھنڈے فریموں میں بہترین۔ گری دار، ہلکا ذائقہ۔" } },
    { name: "Claytonia", diff: 1, desc: "Miner's Lettuce. Exceptionally cold-hardy, tolerating frost into the low teens. Self-sows freely.", varieties: "Claytonia perfoliata (wild type)", notes: "Perfect for winter cold frames and unheated tunnels. Succulent, mild flavor. Thrives in cool weather.", urdu: { name: "کلیٹونیا / کان کن کا سلاد", desc: "غیر معمولی طور پر سردی برداشت، کم نوعمروں تک پالا برداشت کرتا ہے۔ خود بیج بوتا ہے۔", varieties: "کلیٹونیا پرفولیاٹا (جنگلی قسم)", notes: "سردیوں کے ٹھنڈے فریموں اور بغیر حرارت سرنگوں کے لیے بہترین۔ رسیلا، ہلکا ذائقہ۔" } },
  ]},
  { category: "Perennial & Uncommon", icon: "🌿", color: "#2C3E50", bg: "#EBF5FB", items: [
    { name: "Asparagus", diff: 2, desc: "Plant once, harvest 15–20+ years. Full production from year 3. Worth the investment.", varieties: "Jersey Knight (disease-resistant, all-male, CT recommended), Millennium (emerges later, avoids frost), Purple Passion", notes: "All-male varieties (Jersey series) more productive — no energy spent on seeds.", urdu: { name: "ہلیون", desc: "ایک بار لگائیں، 15-20+ سال فصل لیں۔ تیسرے سال سے مکمل پیداوار۔ سرمایہ کاری کے قابل۔", varieties: "جرسی نائٹ (بیماری مزاحم، تمام نر، CT تجویز)، ملینیم (دیر سے نکلتا ہے، پالے سے بچتا ہے)، پرپل پیشن", notes: "تمام نر اقسام (جرسی سیریز) زیادہ پیداواری — بیج پر توانائی خرچ نہیں ہوتی۔" } },
    { name: "Rhubarb", diff: 1, desc: "Extremely low maintenance perennial. Harvest stalks spring–early summer. Do NOT eat leaves (oxalic acid).", varieties: "Canada Red/Macdonald's (most common NE), Valentine, Victoria", notes: "Divide every 5–7 years. Remove flower stalks. Very cold-hardy.", urdu: { name: "ریوند چینی", desc: "انتہائی کم دیکھ بھال والا بارہماسی۔ بہار سے ابتدائی گرما تک ڈنٹھل کاٹیں۔ پتے نہ کھائیں (آکسالک ایسڈ)۔", varieties: "کینیڈا ریڈ/میکڈونلڈز (شمال مشرق میں سب سے عام)، ویلنٹائن، وکٹوریا", notes: "ہر 5-7 سال تقسیم کریں۔ پھول کے ڈنٹھل ہٹائیں۔ بہت سردی برداشت۔" } },
    { name: "Sunchokes", diff: 1, desc: "Native, extremely productive tuber. Grows 6–10 ft with sunflower-like blooms.", varieties: "Stampede (early, 100d), Clearwater", notes: "WARNING: Extremely invasive — use barriers or dedicated area. Cannot be eradicated once established.", urdu: { name: "سن چوک / یروشلم آرٹیچوک", desc: "مقامی، انتہائی پیداواری کند۔ سورج مکھی جیسے پھولوں کے ساتھ 6-10 فٹ اُگتا ہے۔", varieties: "اسٹمپیڈ (ابتدائی، 100 دن)، کلیئر واٹر", notes: "انتباہ: انتہائی حملہ آور — رکاوٹیں یا مخصوص جگہ استعمال کریں۔ قائم ہونے کے بعد ختم نہیں کیا جا سکتا۔" } },
    { name: "Horseradish", diff: 1, desc: "Plant root cuttings spring, harvest after frost. Extremely vigorous.", varieties: "Maliner Kren (standard), Big Top Western", notes: "WARNING: Invasive. Use barriers or dedicated bed. One planting lasts forever.", urdu: { name: "موری سرسوں", desc: "بہار میں جڑ کی قلمیں لگائیں، پالے کے بعد فصل لیں۔ انتہائی توانا۔", varieties: "مالنر کرین (معیاری)، بگ ٹاپ ویسٹرن", notes: "انتباہ: حملہ آور۔ رکاوٹیں یا مخصوص بستر استعمال کریں۔ ایک بار لگانا ہمیشہ کے لیے کافی ہے۔" } },
    { name: "Fiddlehead Ferns", diff: 1, desc: "Ostrich fern ONLY — edible coiled fronds April–May. Native. Plant in shade + moist soil.", varieties: "Matteuccia struthiopteris (Ostrich Fern — the only safe edible fiddlehead)", notes: "Harvest only 2–3 fronds per crown. Cook thoroughly before eating.", urdu: { name: "فڈل ہیڈ فرن", desc: "صرف شتر مرغ فرن — کھانے کے قابل لپٹے ہوئے پتے اپریل-مئی۔ مقامی۔ سایے + نم مٹی میں لگائیں۔", varieties: "میٹیوچیا سٹرتھیوپٹیرس (شتر مرغ فرن — واحد محفوظ کھانے کے قابل فڈل ہیڈ)", notes: "ہر تاج سے صرف 2-3 پتے کاٹیں۔ کھانے سے پہلے اچھی طرح پکائیں۔" } },
    { name: "Sorrel", diff: 1, desc: "Carefree perennial with lemony flavor. Among the first greens in spring.", varieties: "French Sorrel (milder), Common/Garden Sorrel (more tangy)", notes: "Cut-and-come-again. Remove flower stalks to keep producing leaves.", urdu: { name: "ترشک", desc: "بے فکر بارہماسی لیموں جیسے ذائقے کے ساتھ۔ بہار میں پہلی سبزیوں میں سے۔", varieties: "فرنچ ترشک (ہلکا)، عام/باغ ترشک (زیادہ کھٹا)", notes: "کاٹو اور دوبارہ اُگنے دو۔ پتے کی پیداوار جاری رکھنے کے لیے پھول کے ڈنٹھل ہٹائیں۔" } },
    { name: "Groundnuts", diff: 3, desc: "Native nitrogen-fixing vine producing protein-rich tubers. Historically important in CT.", varieties: "Apios americana (wild type and selected cultivars from specialty nurseries)", notes: "Takes 2–3 years for good tuber production. Edible flowers. Beautiful vine.", urdu: { name: "زمینی بادام / اپیوس", desc: "مقامی نائٹروجن فکس کرنے والی بیل جو پروٹین سے بھرپور کند پیدا کرتی ہے۔ تاریخی طور پر کنیکٹیکٹ میں اہم۔", varieties: "اپیوس امریکانا (جنگلی قسم اور خصوصی نرسریوں سے منتخب اقسام)", notes: "اچھی کند پیداوار میں 2-3 سال لگتے ہیں۔ کھانے کے قابل پھول۔ خوبصورت بیل۔" } },
    { name: "Artichokes (annual)", diff: 3, desc: "Grown as annual with cold vernalization trick. Impressive when it works.", varieties: "Imperial Star (bred for first-year production, 85–100d)", notes: "Vernalize seedlings at 45–50°F for 10+ days to trigger bud production.", urdu: { name: "آرٹیچوک (سالانہ)", desc: "ٹھنڈک دینے کی چال کے ساتھ سالانہ کے طور پر اُگایا جاتا ہے۔ جب کام کرے تو متاثر کن۔", varieties: "امپیریل اسٹار (پہلے سال کی پیداوار کے لیے تیار، 85-100 دن)", notes: "کلی کی پیداوار شروع کرنے کے لیے پودوں کو 45-50°F پر 10+ دن ٹھنڈا کریں۔" } },
    { name: "Celeriac", diff: 2, desc: "Easier than celery with same flavor. Good storage root for winter soups and mash.", varieties: "Brilliant, Giant Prague", notes: "Start indoors very early (Feb). Long season but low maintenance once established.", urdu: { name: "سیلریک / گانٹھ اجوائن", desc: "اجوائن سے آسان اسی ذائقے کے ساتھ۔ سردیوں کے سوپ اور میش کے لیے اچھی ذخیرہ جڑ۔", varieties: "بریلینٹ، جائنٹ پراگ", notes: "بہت جلد (فروری) اندر شروع کریں۔ لمبا موسم لیکن قائم ہونے کے بعد کم دیکھ بھال۔" } },
    { name: "Florence Fennel", diff: 2, desc: "Anise-flavored bulb. Fall crop ONLY — bolts in heat.", varieties: "Orion (bolt-resistant), Finale", notes: "Sow July for fall harvest. Direct sow (doesn't transplant well).", urdu: { name: "سونف (فلورنس)", desc: "سونف کے ذائقے والا بلب۔ صرف خزاں کی فصل — گرمی میں بولٹ کر جاتی ہے۔", varieties: "اورئین (بولٹ مزاحم)، فنالے", notes: "خزاں کی فصل کے لیے جولائی میں بوئیں۔ براہ راست بوائی (منتقلی اچھی نہیں ہوتی)۔" } },
    { name: "Hops", diff: 2, desc: "Hardy perennial vine (Zones 3-8). Bines grow 15-25 ft/season. Full production from year 2-3.", varieties: "Cascade (most popular, citrusy), Chinook (piney, bittering), Centennial (floral, dual-purpose)", notes: "Need sturdy trellis. Cut bines to ground after harvest. Useful for homebrewing, teas, ornamental screen.", urdu: { name: "ہاپس", desc: "سخت جان بارہماسی بیل (زون 3-8)۔ بیلیں 15-25 فٹ/موسم بڑھتی ہیں۔ سال 2-3 سے مکمل پیداوار۔", varieties: "کاسکیڈ (سب سے مقبول، لیموں والا)، شنوک (صنوبری، کڑواہٹ)، سینٹینیل (پھول دار، دوہرا مقصد)", notes: "مضبوط ٹریلس ضروری۔ فصل کے بعد بیلیں زمین تک کاٹ دیں۔ گھریلو شراب سازی، چائے، سجاوٹی پردے کے لیے مفید۔" } },
  ]},
  { category: "Herbs", icon: "🌱", color: "#117A65", bg: "#E8F8F5", items: [
    { name: "Thyme", diff: 1, desc: "Hardy perennial returning yearly (Zones 5–9).", varieties: "English Thyme, Lemon Thyme, Creeping Thyme (ground cover)", notes: "Excellent drainage essential. Divide every 3–4 years.", urdu: { name: "تھائم / آجوائن خراسانی", desc: "سخت جان بارہماسی ہر سال واپس آتا ہے (زون 5-9)۔", varieties: "انگلش تھائم، لیمن تھائم، رینگنے والا تھائم (زمینی ڈھانپنا)", notes: "بہترین نکاسی ضروری۔ ہر 3-4 سال تقسیم کریں۔" } },
    { name: "Oregano", diff: 1, desc: "Extremely hardy perennial. Flavor intensifies when dried.", varieties: "Greek Oregano (best culinary flavor), Italian Oregano", notes: "Spreads readily. Greek type preferred for cooking vs. ornamental types.", urdu: { name: "اوریگانو", desc: "انتہائی سخت جان بارہماسی۔ خشک ہونے پر ذائقہ تیز ہو جاتا ہے۔", varieties: "یونانی اوریگانو (بہترین کھانے کا ذائقہ)، اطالوی اوریگانو", notes: "آسانی سے پھیلتا ہے۔ کھانا پکانے کے لیے یونانی قسم ترجیح۔" } },
    { name: "Sage", diff: 1, desc: "Beautiful ornamental and culinary perennial (Zones 5–10). Semi-evergreen.", varieties: "Common/Garden Sage, Purple Sage, Tricolor Sage", notes: "Prune woody growth spring. Replace every 4–5 years as plants get leggy.", urdu: { name: "سیج / بری تلسی", desc: "خوبصورت سجاوٹی اور کھانے کا بارہماسی (زون 5-10)۔ نیم سدا بہار۔", varieties: "عام/باغ سیج، جامنی سیج، تین رنگا سیج", notes: "بہار میں لکڑی والی نشوونما کی کٹائی کریں۔ ہر 4-5 سال بدلیں جب پودے لمبے ہو جائیں۔" } },
    { name: "Chives", diff: 1, desc: "Among the very first to emerge spring (Zones 3–9). Edible purple flowers.", varieties: "Common Chives, Garlic Chives (flat leaves, garlic flavor)", notes: "Self-sows readily — deadhead to prevent spreading. Divide every 3 years.", urdu: { name: "چائیوز / گندنا", desc: "بہار میں سب سے پہلے نکلنے والوں میں سے (زون 3-9)۔ کھانے کے قابل جامنی پھول۔", varieties: "عام چائیوز، لہسن چائیوز (چپٹے پتے، لہسن کا ذائقہ)", notes: "خود آسانی سے بیج بوتا ہے — پھیلاؤ روکنے کے لیے مردہ پھول ہٹائیں۔ ہر 3 سال تقسیم کریں۔" } },
    { name: "Mint", diff: 1, desc: "Aggressively spreading perennial. ALWAYS grow in containers or isolated beds.", varieties: "Spearmint, Peppermint, Chocolate Mint, Mojito Mint", notes: "Will take over entire garden. Containers on patio safest approach.", urdu: { name: "پودینہ", desc: "جارحانہ طور پر پھیلنے والا بارہماسی۔ ہمیشہ گملوں یا الگ بستروں میں اُگائیں۔", varieties: "سپیئرمنٹ، پیپرمنٹ، چاکلیٹ منٹ، موہیٹو منٹ", notes: "پورا باغ لے لے گا۔ آنگن میں گملے سب سے محفوظ طریقہ۔" } },
    { name: "French Tarragon", diff: 2, desc: "True French tarragon doesn't set seed — must be grown from divisions or cuttings.", varieties: "French Tarragon (NOT Russian — Russian has inferior flavor)", notes: "Zones 4–8. Verify 'French' by tasting — should tingle/numb tongue slightly.", urdu: { name: "فرنچ ترخون", desc: "اصل فرنچ ترخون بیج نہیں بناتا — تقسیم یا قلموں سے اُگانا ضروری۔", varieties: "فرنچ ترخون (روسی نہیں — روسی کا ذائقہ کمتر ہے)", notes: "زون 4-8۔ ذائقے سے 'فرنچ' کی تصدیق کریں — زبان پر ہلکی سی جھنجھناہٹ/سنسناہٹ ہونی چاہیے۔" } },
    { name: "Lovage", diff: 1, desc: "Towering celery-flavored perennial. One plant is enough — grows 6 ft tall.", varieties: "Common Lovage (Levisticum officinale)", notes: "Zones 4–8. Use leaves, stems, and seeds. Excellent celery substitute.", urdu: { name: "لووج", desc: "اونچا اجوائن کے ذائقے والا بارہماسی۔ ایک پودا کافی ہے — 6 فٹ اونچا ہوتا ہے۔", varieties: "عام لووج (لیوسٹیکم آفیسینالے)", notes: "زون 4-8۔ پتے، تنے اور بیج استعمال کریں۔ بہترین اجوائن کا متبادل۔" } },
    { name: "Basil", diff: 1, desc: "Annual. Killed instantly by frost. Start indoors or direct sow after May 15.", varieties: "Genovese (pesto standard), Thai Basil, Lemon Basil, Purple Basil", notes: "Pinch flowers to keep producing leaves. Downy mildew increasing concern in NE.", urdu: { name: "تلسی / نیازبو", desc: "سالانہ۔ پالے سے فوری طور پر مر جاتا ہے۔ اندر شروع کریں یا 15 مئی کے بعد براہ راست بوئیں۔", varieties: "جینووز (پیسٹو معیاری)، تھائی تلسی، لیمن تلسی، جامنی تلسی", notes: "پتے کی پیداوار جاری رکھنے کے لیے پھول نوچ دیں۔ شمال مشرق میں پھپھوندی بڑھتی تشویش۔" } },
    { name: "Cilantro", diff: 1, desc: "Bolts rapidly in heat. Best spring and fall. Let some go to seed for coriander.", varieties: "Calypso (slow-bolt, best for leaf production), Santo", notes: "Succession sow every 3 weeks spring and fall. Summer production is futile.", urdu: { name: "دھنیا", desc: "گرمی میں تیزی سے بولٹ کرتا ہے۔ بہار اور خزاں میں بہترین۔ کچھ بیج بننے دیں۔", varieties: "کیلیپسو (سست بولٹ، پتوں کی پیداوار کے لیے بہترین)، سانتو", notes: "بہار اور خزاں میں ہر 3 ہفتے بوائی کریں۔ گرمیوں کی پیداوار بے سود ہے۔" } },
    { name: "Dill", diff: 1, desc: "Essential for pickles. Self-sows freely. Attracts beneficial insects.", varieties: "Fernleaf (compact, slow bolt), Bouquet (tall, for seed heads/pickles)", notes: "Self-sows reliably. Fernleaf better for leaf harvest, Bouquet for seed heads.", urdu: { name: "سویا / شبت", desc: "اچار کے لیے ضروری۔ خود آزادانہ بیج بوتا ہے۔ فائدہ مند کیڑوں کو کھینچتا ہے۔", varieties: "فرن لیف (چھوٹا، سست بولٹ)، بوکے (لمبا، بیج کے سروں/اچار کے لیے)", notes: "قابل اعتماد طور پر خود بیج بوتا ہے۔ فرن لیف پتوں کی فصل کے لیے بہتر، بوکے بیج کے سروں کے لیے۔" } },
    { name: "Parsley", diff: 1, desc: "Biennial — overwinters with mulch, bolts year 2. Slow to germinate (2–3 weeks).", varieties: "Italian Flat-Leaf (best flavor), Curly Parsley (garnish)", notes: "Soak seeds overnight. Can overwinter under mulch for very early spring harvest.", urdu: { name: "اجمود", desc: "دو سالہ — ملچ کے ساتھ سردیاں گزارتا ہے، دوسرے سال بولٹ کرتا ہے۔ اُگنے میں سست (2-3 ہفتے)۔", varieties: "اطالوی چپٹے پتے (بہترین ذائقہ)، گھنگھریالا اجمود (سجاوٹ)", notes: "بیج رات بھر بھگو دیں۔ بہت ابتدائی بہار کی فصل کے لیے ملچ کے نیچے سردیاں گزار سکتا ہے۔" } },
    { name: "Rosemary", diff: 4, desc: "NOT reliably hardy in Zone 6b. CT growers report it dying every single year outdoors.", varieties: "Arp (hardiest, rated Zone 6 with protection), Madeline Hill", notes: "Grow in containers brought indoors for winter. Or treat as annual. Arp in sheltered south-facing spot = possible.", urdu: { name: "روزمیری / اکلیل الجبل", desc: "زون 6b میں قابل اعتماد طور پر سخت جان نہیں۔ کنیکٹیکٹ کے کاشتکار باہر ہر سال مرنے کی اطلاع دیتے ہیں۔", varieties: "آرپ (سب سے سخت جان، حفاظت کے ساتھ زون 6)، میڈلین ہل", notes: "سردیوں کے لیے گملوں میں اندر لائیں۔ یا سالانہ کے طور پر رکھیں۔ محفوظ جنوبی جگہ میں آرپ = ممکن۔" } },
  ]},
];

const DIFF = { 1: { label: "Easy", color: "#27AE60", dots: "●○○○" }, 2: { label: "Moderate", color: "#F39C12", dots: "●●○○" }, 3: { label: "Challenging", color: "#E67E22", dots: "●●●○" }, 4: { label: "Gamble", color: "#C0392B", dots: "●●●●" } };

// Map items that share a wiki key to their unique fallback key
const UNIQUE_IMAGE_KEY = {
  "Nectarines": "Nectarine",
  "Raspberries (Fall-bearing)": "Raspberry_fall",
  "Strawberries (Day-neutral)": "Strawberry_dayneutral",
  "Grapes (Wine)": "Grape_wine",
};

const ur = { direction: "rtl", textAlign: "right", fontFamily: "'Noto Nastaliq Urdu', 'Jameel Noori Nastaleeq', serif", color: "#7A6B5A" };

function ItemCard({ item, images }) {
  const d = DIFF[item.diff];
  const u = item.urdu;
  const wikiKey = WIKI_ITEMS[item.name];
  const uniqueKey = UNIQUE_IMAGE_KEY[item.name];
  const imgUrl = uniqueKey ? (FALLBACK_IMAGES[uniqueKey] || images[uniqueKey]) : (wikiKey ? images[wikiKey] : null);
  return (
    <div className="item-card" style={{ display: "grid", gridTemplateColumns: "72px 1fr", gap: 10, padding: "10px 8px", borderBottom: "1px solid #e8e8e3", pageBreakInside: "avoid", breakInside: "avoid" }}>
      <div style={{ width: 72, height: 72, borderRadius: 10, overflow: "hidden", background: "#f0ede8", flexShrink: 0, alignSelf: "start" }}>
        {imgUrl ? <img src={imgUrl} alt={item.name} style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} /> : <div style={{ width: "100%", height: "100%", background: "#e8e4de", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, color: "#aaa", fontFamily: "'DM Sans', sans-serif", textAlign: "center", padding: 4, lineHeight: 1.2 }}>{item.name.split(/[\s/]/)[0]}</div>}
      </div>
      <div style={{ minWidth: 0 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 8, marginBottom: 3 }}>
          <div style={{ display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" }}>
            <span style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontSize: 15, fontWeight: 700, color: "#2C3E2D", lineHeight: 1.2 }}>{item.name}</span>
            {u && <span style={{ ...ur, fontSize: 12, fontWeight: 700, lineHeight: 1.4 }}>{u.name}</span>}
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 8, flexShrink: 0 }}>
            <span style={{ fontSize: 9, fontWeight: 600, color: d.color, whiteSpace: "nowrap" }}>{d.dots} {d.label}</span>
            <span style={{ fontSize: 14, color: "#ccc", letterSpacing: 2 }}>☐☐☐☐</span>
          </div>
        </div>
        <div style={{ fontSize: 10, color: "#666", lineHeight: 1.4, marginBottom: 2 }}>{item.desc}</div>
        <div style={{ fontSize: 10, lineHeight: 1.4, marginBottom: 2 }}>
          <span style={{ color: "#1E6B3A", fontWeight: 700, fontSize: 9, textTransform: "uppercase", letterSpacing: 0.3 }}>Varieties: </span>{item.varieties}
        </div>
        <div style={{ fontSize: 9, color: "#999", fontStyle: "italic", lineHeight: 1.35, marginBottom: 0 }}>{item.notes}</div>
        {u && <div style={{ borderTop: "1px dashed #e0dcd6", marginTop: 6, paddingTop: 4 }}>
          <div style={{ ...ur, fontSize: 10, lineHeight: 1.6, marginBottom: 2 }}>{u.desc}</div>
          <div style={{ ...ur, fontSize: 9, lineHeight: 1.6, marginBottom: 2 }}><span style={{ color: "#1E6B3A", fontWeight: 700 }}>اقسام: </span>{u.varieties}</div>
          <div style={{ ...ur, fontSize: 9, lineHeight: 1.6, color: "#9B8E7E", fontStyle: "italic" }}>{u.notes}</div>
        </div>}
      </div>
    </div>
  );
}

function RefSection({ title, children }) {
  return (
    <div className="ref-section" style={{ marginBottom: 16 }}>
      <div style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontSize: 14, fontWeight: 700, color: "#2C3E2D", borderBottom: "2px solid #e8e8e3", paddingBottom: 4, marginBottom: 8 }}>{title}</div>
      {children}
    </div>
  );
}

function RefItem({ text }) {
  return <div style={{ fontSize: 10, color: "#444", lineHeight: 1.5, paddingLeft: 14, position: "relative", marginBottom: 3 }}><span style={{ position: "absolute", left: 0, color: "#1E6B3A", fontWeight: 700 }}>•</span><span dangerouslySetInnerHTML={{ __html: text }} /></div>;
}

export default function GrowGuide() {
  const [images, setImages] = useState({});
  const [loading, setLoading] = useState(true);
  const [loaded, setLoaded] = useState(0);
  const allWikiKeys = [...new Set(Object.values(WIKI_ITEMS))];
  const total = allWikiKeys.length;

  useEffect(() => {
    let m = true;
    (async () => {
      const r = {};
      for (let i = 0; i < allWikiKeys.length; i += 10) {
        const batch = allWikiKeys.slice(i, i + 10);
        await Promise.all(batch.map(async (k) => { try { const d = await (await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(k)}`)).json(); if (d.thumbnail?.source) r[k] = d.thumbnail.source.replace(/\/\d+px-/, "/200px-"); } catch {} }));
        if (m) setLoaded(Math.min(i + 10, allWikiKeys.length));
      }
      // Apply fallback images for missing/broken thumbnails
      for (const [key, url] of Object.entries(FALLBACK_IMAGES)) {
        if (!r[key]) r[key] = url;
      }
      if (m) { setImages(r); setLoading(false); }
    })();
    return () => { m = false; };
  }, []);

  const totalItems = DATA.reduce((s, c) => s + c.items.length, 0);
  const tbl = { fontSize: 10, borderCollapse: "collapse", width: "100%" };
  const th = { background: "#e8e8e3", textAlign: "left", padding: "5px 10px", fontWeight: 600, fontSize: 10 };
  const td = { padding: "4px 10px", borderBottom: "1px solid #eee", fontSize: 10 };

  return (
    <div style={{ fontFamily: "'DM Sans', -apple-system, sans-serif", background: "#fafaf8", color: "#333", maxWidth: 850, margin: "0 auto", padding: "12px 16px" }}>
      <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,400;0,600;0,700;1,400&family=DM+Sans:wght@400;500;600;700&family=Noto+Nastaliq+Urdu:wght@400;700&display=swap" rel="stylesheet" />
      <style>{`
        @media print {
          body { background: #fff !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          @page { margin: 0.4in 0.5in; size: letter; }
          .no-print { display: none !important; }
          .page-break { page-break-before: always; break-before: page; }
          .category-section { break-inside: avoid-page; }
          .category-header { break-after: avoid; }
          .item-card { break-inside: avoid; page-break-inside: avoid; }
          .ref-section { break-inside: avoid; page-break-inside: avoid; }
          table { break-inside: avoid; page-break-inside: avoid; }
          tr { break-inside: avoid; page-break-inside: avoid; }
          img { break-inside: avoid; }
          h1, h2, h3, h4 { break-after: avoid; page-break-after: avoid; }
        }
      `}</style>

      {/* Header */}
      <div style={{ background: "linear-gradient(135deg, #2C3E2D, #4A6741)", color: "#fff", padding: "18px 22px", borderRadius: 8, marginBottom: 12 }}>
        <div style={{ fontSize: 9, letterSpacing: 2, textTransform: "uppercase", opacity: 0.7, marginBottom: 4 }}>New Milford, CT · USDA Zone 6b</div>
        <div style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontSize: 32, fontWeight: 700, fontStyle: "italic", lineHeight: 1.1 }}>What You Can Grow</div>
        <div style={{ fontSize: 10, opacity: 0.75, marginTop: 6 }}>
          {totalItems} varieties across {DATA.length} categories · ~150-day growing season · Last frost ≈ Apr 26 · First frost ≈ Oct 24
          {loading && <span className="no-print" style={{ marginLeft: 12, opacity: 0.6 }}>📷 Loading images ({loaded}/{total})...</span>}
        </div>
      </div>

      {/* Legend */}
      <div style={{ display: "flex", flexWrap: "wrap", gap: "6px 16px", fontSize: 9, color: "#666", padding: "8px 12px", border: "1px solid #e8e8e3", borderRadius: 6, marginBottom: 12, background: "#fefefe" }}>
        <span><b>Difficulty:</b></span>
        {Object.entries(DIFF).map(([k, v]) => <span key={k} style={{ color: v.color }}>{v.dots} {v.label}</span>)}
        <span style={{ marginLeft: "auto" }}><b>Checkboxes:</b> ☐ Researched · ☐ Acquired · ☐ Planted · ☐ Harvested</span>
      </div>

      {/* Categories */}
      {DATA.map((cat) => (
        <div key={cat.category} className="category-section" style={{ marginBottom: 16 }}>
          <div className="category-header" style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "10px 14px", borderRadius: "6px 6px 0 0", background: cat.bg, color: cat.color, borderBottom: `3px solid ${cat.color}` }}>
            <div style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontSize: 18, fontWeight: 700 }}>{cat.icon} {cat.category}</div>
            <div style={{ fontSize: 10, fontWeight: 600, opacity: 0.8 }}>{cat.items.length} varieties</div>
          </div>
          {cat.items.map((item) => <ItemCard key={item.name} item={item} images={images} />)}
        </div>
      ))}

      {/* ═══════ QUICK REFERENCE ═══════ */}
      <div className="page-break" style={{ marginTop: 32 }}>
        <div style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontSize: 24, fontWeight: 700, color: "#2C3E2D", marginBottom: 16 }}>Quick Reference</div>

        <RefSection title="Key Dates for New Milford, CT">
          <table style={tbl}>
            <thead><tr><th style={th}>Event</th><th style={th}>Date</th></tr></thead>
            <tbody>
              {[
                ["Last spring frost (average)", "April 26"],
                ["Safe transplant date (tender crops)", "May 10–15"],
                ["Latest recorded spring frost", "May 18 (2023)"],
                ["Start warm crops indoors", "Late March – Early April"],
                ["Direct sow cool crops outdoors", "Mid-April (when soil workable)"],
                ["Transplant tender crops outdoors", "After May 15"],
                ["Sow fall crops", "Late July – August"],
                ["First fall frost (average)", "October 24"],
                ["Conservative first frost (plan for)", "October 10–15"],
                ["Plant garlic", "Mid-October"],
                ["Frost-free growing season", "~150–160 days"],
                ["AHS Heat Zone", "4–5 (15–30 days above 86°F)"],
              ].map(([a, b], i) => <tr key={i} style={{ background: i % 2 ? "#fafaf8" : "#fff" }}><td style={td}>{a}</td><td style={td}>{b}</td></tr>)}
            </tbody>
          </table>
        </RefSection>

        <RefSection title="Soil & Site — New Milford Specifics">
          <RefItem text="CT soils typically <b>pH 4.8–5.5</b>. Most vegetables need pH 6.0–6.8 — liming required." />
          <RefItem text="<b>Exception:</b> blueberries, potatoes, rhododendrons PREFER CT's natural acidity — no amendment needed." />
          <RefItem text="New Milford's <b>marble/limestone bedrock</b> may naturally buffer soil toward neutral in some locations — a significant advantage worth confirming with a soil test." />
          <RefItem text="<b>UConn Soil Lab:</b> $12 test at soiltesting.cahnr.uconn.edu. Test every 3–5 years." />
          <RefItem text="<b>Raised beds</b> with quality topsoil-compost mix bypass rocky glacial till entirely — strongly recommended by UConn Extension." />
          <RefItem text="Apply <b>dolomitic limestone</b> in fall (5–7 lbs per 100 sq ft max). Supplies calcium and magnesium." />
          <RefItem text="<b>Housatonic River valley</b> provides fertile alluvial soils and slight thermal moderation. Valley bottoms can be frost pockets where cold air pools; south-facing slopes a few feet above are warmer." />
          <RefItem text="Annual precipitation ~<b>49 inches</b>, well-distributed — ample for most crops but humid enough to fuel fungal diseases." />
        </RefSection>

        <RefSection title="Top Challenges & Solutions">
          <RefItem text="<b>Deer (#1 threat):</b> 8-ft fence is the only reliable solution. Repellents require constant rotation and reapplication. Solid 6-ft stockade fences work because deer won't jump what they can't see through." />
          <RefItem text="<b>Japanese beetles (peak Jun–Aug):</b> Hand-pick into soapy water ~7 PM (most effective). Use beneficial nematodes, NOT milky spore (doesn't work in NE cool soils). Avoid pheromone traps near garden — they attract more beetles." />
          <RefItem text="<b>Spotted lanternfly:</b> Now established in Litchfield County with CAES quarantine orders. Kill on sight. Scrape egg masses (Sept–May). Remove tree-of-heaven (preferred host). Feeds on grapes, hops, fruit trees." />
          <RefItem text="<b>Squash vine borers:</b> Row covers from planting until flowering. Late planting (July) dodges June egg-laying. <b>Butternut squash</b> (C. moschata) and <b>Tromboncino</b> are naturally resistant/immune." />
          <RefItem text="<b>Late blight (tomatoes/potatoes):</b> Can destroy plants within a week. Choose resistant varieties (Mountain Merit, Kennebec). Monitor USAblight.org for regional outbreaks." />
          <RefItem text="<b>Apple scab:</b> Controlled most effectively by planting resistant varieties (Liberty, Enterprise, GoldRush). CT's humidity makes it nearly inevitable on susceptible varieties." />
          <RefItem text="<b>Late spring frosts (as late as May 18):</b> Keep row covers and old blankets ready. Choose late-blooming fruit cultivars (Contender peach, Duke blueberry, Goldcot apricot). Plant stone fruit on north-facing slopes." />
          <RefItem text="<b>Cucumber beetles:</b> Transmit bacterial wilt, devastating to cucumbers and muskmelons. Row covers until flowering are the primary defense." />
        </RefSection>

        <RefSection title="Season Extension">
          <RefItem text="<b>Floating row covers</b> add 2–5°F protection. Essential for early transplants and late fall harvests." />
          <RefItem text="<b>Low tunnels/cold frames</b> enable harvest of hardy greens (kale, spinach, tatsoi) into December or even through winter." />
          <RefItem text="<b>High tunnels</b> can create a 200+ day effective season. USDA NRCS EQIP program provides financial assistance." />
          <RefItem text="<b>Black plastic mulch</b> warms soil 5–10°F earlier — mandatory for melons, sweet potatoes, eggplant, peppers in CT." />
          <RefItem text="<b>Water-filled cloches</b> (Wall O' Water) protect individual transplants from frosts 2–3 weeks before safe date." />
        </RefSection>

        <RefSection title="Essential CT Resources">
          <RefItem text="<b>UConn Home & Garden Education Center:</b> homegarden.cahnr.uconn.edu — staffed horticulturists, diagnostic services, fact sheets. Phone: 877-486-6271" />
          <RefItem text="<b>UConn Soil Nutrient Analysis Lab:</b> soiltesting.cahnr.uconn.edu — standard test $12" />
          <RefItem text="<b>CT Agricultural Experiment Station:</b> portal.ct.gov/caes — disease diagnostics, spray guides, pest fact sheets" />
          <RefItem text="<b>New England Vegetable Management Guide:</b> nevegetable.org — premier crop-by-crop reference for the region" />
          <RefItem text="<b>Seed companies (NE-focused):</b> Fedco Seeds (fedcoseeds.com), Johnny's Selected Seeds (johnnyseeds.com) — specialize in short-season, cold-hardy varieties" />
          <RefItem text="<b>Berry plants:</b> Nourse Farms — first choice for strawberries, raspberries, blackberries, currants" />
          <RefItem text="<b>CT nurseries:</b> Cricket Hill Garden (Thomaston, CT) — unusual plants including medlar, che fruit, tree peonies" />
        </RefSection>

        <RefSection title="CT Grower Tips (from Reddit, Permies, OurFigs forums)">
          <RefItem text="A Litchfield County orchardist with 41 fruit trees: <b>Asian pears performed spectacularly</b> while European pears refused to produce and sweet cherries failed due to humidity." />
          <RefItem text="<b>Apricots were a near-total loss</b> — multiple growers confirm this across western CT. Don't plant unless you enjoy the gamble." />
          <RefItem text="One CT family has grown <b>in-ground fig trees for 90+ years</b> using winter wrapping — another harvests ~1,300 figs/year from 3 trees." />
          <RefItem text="Universally cited: <b>'Between the deer and the Japanese beetles, I don't know who's worse.'</b> Invest in fencing BEFORE planting." />
          <RefItem text="A Thomaston food forest grower reports success with apples, Illinois Everbearing mulberry, medlar, cornelian cherry, garlic, and Asian pears on sandy-loam soil." />
          <RefItem text="<b>Sungold cherry tomato</b> is the single most recommended variety across all CT gardening forums." />
        </RefSection>
      </div>

      {/* ═══════ NOTES PAGE ═══════ */}
      <div className="page-break" style={{ marginTop: 32 }}>
        <div style={{ fontFamily: "'Crimson Pro', Georgia, serif", fontSize: 24, fontWeight: 700, color: "#2C3E2D", marginBottom: 6 }}>Notes & Planning</div>
        <div style={{ fontSize: 10, color: "#666", marginBottom: 16 }}>Use this page for planting dates, soil test results, seed orders, layout sketches, and observations.</div>
        {Array.from({ length: 30 }).map((_, i) => <div key={i} style={{ borderBottom: "1px solid #e8e8e3", height: 26 }} />)}
      </div>

      {/* Footer */}
      <div style={{ textAlign: "center", fontSize: 8, color: "#bbb", padding: "12px 0", borderTop: "1px solid #e8e8e3", marginTop: 16 }}>
        New Milford, CT Grow Guide · Zone 6b · Sources: UConn Extension, CT Agricultural Experiment Station, NE Vegetable Management Guide, Reddit/Permies/OurFigs community reports
      </div>
    </div>
  );
}